### ISSUE TITLE
-webkit-linear-gradient doesn't work...

### ISSUE THREAD

**Issue by totty90** [Compass/compass#1725] opened 2014-07-17 15:47 UTC
```
                    background: -webkit-linear-gradient(
                        left,
                        #0193CD 30%,
                        #66D4E5 80%,
                        #0193CD 100%
                    ) repeat;
```

This will not output the css at all. Using grunt compass for scss

Also -webkit-gradient doesn't work.

**Comment by chriseppstein** [comment] 2014-07-17 17:05
I cannot reproduce this. Please provide a complete sass file that exhibits this issue and tell me how you are compiling it and with what versions of software.

**Comment by chriseppstein** [comment] 2014-08-01 17:23
Closing due to lack of reply.

**Closed as completed by chriseppstein** 2014-08-01 17:23 UTC

**Comment by vietnogi** [comment] 2014-08-20 17:51
Probably due to autoprefixer, may have to change `last 1 version` to 2 or 3
