### ISSUE TITLE
Corrupt PNG - System Crash

### ISSUE THREAD

**Issue by gigafied** [Compass/compass#1104] opened 2012-11-24 03:21 UTC
Somehow (don't ask me how), a PSD file got saved as a PNG file and checked into the project. The PSD was smallish (33 KB), so it wasn't super obvious.

Anyway, basically when I tried to compile a sprite sheet, ruby ended up leaking a huge amount of memory, (in Activity Monitor, it showed over 13GB of actual used memory).

This is, of course, insane, there needs to be a better way of handling and catching something like this. The first time I tried it, the process just hung (terminal was in the background and I was doing something else), all of a sudden my comp just crashed. When I rebooted and tried to run it again, I noticed the hung process and opened Activity Monitor.

Took me a lot of trial and error to discover the issue and the PSD saved as a PNG. Ideally, Compass/ChunkyPNG would be able to spit some kind of warning/error out.

I'm not sure if this is a ChunkyPNG or Compass error however.

Closely related to: https://github.com/chriseppstein/compass/issues/860

**Comment by scottdavis** [comment] 2013-01-17 22:45
I would say this is a ChunkyPng error if it was leaking memory and not throwing an error. @wvanbergen

**Comment by wvanbergen** [comment] 2013-01-18 00:56
Last time we saw this issue, it was compass not handling the ChunkyPNG exception properly. ChunkyPNG raises an exception right away if a file doesn't start with the PNG header.
I can look into it but I'll need access to the file you were using.Also: are you using oily_png as well?

**Comment by wvanbergen** [comment] 2013-01-18 01:02
The file referenced in the other issue correctly generates an exception for me:

```
~/Code $ wget http://thomas.clicklabs.co.uk/corrupt-png-compass-test.png
--2013-01-17 20:01:50--  http://thomas.clicklabs.co.uk/corrupt-png-compass-test.png
Resolving thomas.clicklabs.co.uk... 31.222.169.251
Connecting to thomas.clicklabs.co.uk|31.222.169.251|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2437 (2.4K) [image/png]
Saving to: `corrupt-png-compass-test.png'

100%[========================================================================================>] 2,437       --.-K/s   in 0s      

2013-01-17 20:01:50 (72.6 MB/s) - `corrupt-png-compass-test.png' saved [2437/2437]

~/Code $ ruby -rrubygems -rchunky_png -e "ChunkyPNG::Image.from_file('corrupt-png-compass-test.png')"
/Users/willem/.rvm/gems/ruby-1.9.3-p327/gems/chunky_png-1.2.7/lib/chunky_png/datastream.rb:102:in `verify_signature!': PNG signature not found! (ChunkyPNG::SignatureMismatch)
    from /Users/willem/.rvm/gems/ruby-1.9.3-p327/gems/chunky_png-1.2.7/lib/chunky_png/datastream.rb:74:in `from_io'
    from /Users/willem/.rvm/gems/ruby-1.9.3-p327/gems/chunky_png-1.2.7/lib/chunky_png/datastream.rb:66:in `block in from_file'
    from /Users/willem/.rvm/gems/ruby-1.9.3-p327/gems/chunky_png-1.2.7/lib/chunky_png/datastream.rb:66:in `open'
    from /Users/willem/.rvm/gems/ruby-1.9.3-p327/gems/chunky_png-1.2.7/lib/chunky_png/datastream.rb:66:in `from_file'
    from /Users/willem/.rvm/gems/ruby-1.9.3-p327/gems/chunky_png-1.2.7/lib/chunky_png/canvas/png_decoding.rb:53:in `from_file'
    from -e:1:in `<main>'
```

Exception to watch: `ChunkyPNG::SignatureMismatch`

**Comment by scottdavis** [comment] 2013-01-18 01:10
https://github.com/chriseppstein/compass/blob/master/lib/compass/sass_extensions/sprites/engines/chunky_png_engine.rb#L17-L19

Although, I didn't think about it he could be using an older version of compass ...

Also have you tried a PSD i don't have Photoshop atm

**Comment by gigafied** [comment] 2013-01-18 03:10
I should have supplied version numbers I was using when I submitted the issue, sorry.

I believe I haven't upgraded them on the project since I had this issue, so here's what they are:

Compass - 0.12.2
ChunkyPNG - 1.2.6
OilyPNG - 1.0.2

I can verify I am still having the issue tomorrow, but it definitely could be OilyPNG and to be fair, there is a warning in OilyPNGs README that says:

"Warning: this is my first C code in years. It may blow up your PC after leaking memory all over the place, killing a kitten in the process. You have been warned."

**Comment by wvanbergen** [comment] 2013-01-20 15:39
The use of oily_png should not matter in this case, because loading the image already fails before oily_png kicks in (it only does things during the actual decoding phase). However, seeing whether you have the same problem without oily_png would be interesting.

In the end, I think it is more likely that the bug is somewhere in Compass, because ChunkyPNG never keeps more stuff in memory than just the image you are working on. My best guess is the ChunkyPNG instance isn't disposed of properly after an exception is thrown, but I have no way of proving this.

**Comment by henrahmagix** [comment] 2013-01-24 17:31
This was completely reproducible with Compass 0.13.alpha.0 when compiling sprites. Not doing anything with ChunkyPNG or OilyPNG separately - just calling `compass watch` on a project with sprites.

The following from #860 description is exactly what I experienced:

> I reopened photoshop, re-saved the file and everything was fine. I'm not sure what was wrong with the image as it opened and displayed in Preview, but opening it in photoshop I got this error "Could not complete your request because the file-format module cannot parse the file."

**Comment by scottdavis** [comment] 2013-01-24 17:39
Do you still have the offending file we could use as a test?

**Comment by henrahmagix** [comment] 2013-01-24 17:42
Unfortunately no, sorry =(

I will try the simple rename JPG to PNG and post that if it is _correctly corrupt._

**Comment by henrahmagix** [comment] 2013-01-24 18:01
Opened PNG in Preview and saved as JPG (using _Export..._ option) resulted in this:

```
ruby(23844) malloc: *** mmap(size=162052923432370176) failed (error code=12)
*** error: can't allocate region
*** set a breakpoint in malloc_error_break to debug
ruby(23844) malloc: *** mmap(size=162052923432370176) failed (error code=12)
*** error: can't allocate region
*** set a breakpoint in malloc_error_break to debug
NoMemoryError on line 87 of /Library/Ruby/Gems/1.8/gems/chunky_png-1.2.5/lib/chunky_png/canvas.rb: failed to allocate memory
Run with --trace to see the full backtrace
```

Top few lines of `--trace`

```
NoMemoryError on line 87 of /Library/Ruby/Gems/1.8/gems/chunky_png-1.2.5/lib/chunky_png/canvas.rb: failed to allocate memory
  /Library/Ruby/Gems/1.8/gems/chunky_png-1.2.5/lib/chunky_png/canvas.rb:87:in `new'
  /Library/Ruby/Gems/1.8/gems/chunky_png-1.2.5/lib/chunky_png/canvas.rb:87:in `initialize'
  /Library/Ruby/Gems/1.8/gems/chunky_png-1.2.5/lib/chunky_png/image.rb:23:in `initialize'
  /Library/Ruby/Gems/1.8/gems/compass-0.13.alpha.0/lib/compass/sass_extensions/sprites/engines/chunky_png_engine.rb:13:in `new'
  /Library/Ruby/Gems/1.8/gems/compass-0.13.alpha.0/lib/compass/sass_extensions/sprites/engines/chunky_png_engine.rb:13:in `construct_sprite'
  /Library/Ruby/Gems/1.8/gems/compass-0.13.alpha.0/lib/compass/sass_extensions/sprites/sprite_methods.rb:53:in `generate'
  /Library/Ruby/Gems/1.8/gems/compass-0.13.alpha.0/lib/compass/sass_extensions/functions/sprites.rb:127:in `sprite_url'
  /Library/Ruby/Gems/1.8/gems/compass-0.13.alpha.0/lib/compass/sass_extensions/sprites/sprite_map.rb:71:in `send'
  /Library/Ruby/Gems/1.8/gems/compass-0.13.alpha.0/lib/compass/sass_extensions/sprites/sprite_map.rb:71:in `method_missing'
  /Library/Ruby/Gems/1.8/gems/compass-0.13.alpha.0/lib/compass/sass_extensions/sprites/sprite_map.rb:62:in `to_s'
  /Library/Ruby/Gems/1.8/gems/sass-3.2.3/lib/sass/../sass/script/list.rb:44:in `to_s'
  /Library/Ruby/Gems/1.8/gems/sass-3.2.3/lib/sass/../sass/script/list.rb:44:in `map'
  /Library/Ruby/Gems/1.8/gems/sass-3.2.3/lib/sass/../sass/script/list.rb:44:in `to_s'
```

However, renaming native JPG to PNG caused the known error of memory-nomming.

File: 
![bucket-of-cries](https://f.cloud.github.com/assets/1429026/94577/f39e4458-664f-11e2-9248-5bdba6d354d6.png)

Sorry if that image creeps you out! Random photoshopping from a friend and it was the first JPG I found on my Desktop =)

**Comment by scottdavis** [comment] 2013-01-24 18:06
And this is the version on the master branch?

**Comment by henrahmagix** [comment] 2013-01-24 22:28
Sorry @scottdavis, got confused there. I'm not entirely sure. It's certainly outdated; will check in the morning =)

**Comment by henrahmagix** [comment] 2013-01-25 09:43
@scottdavis A few months ago I ran `gem install compass --pre` to get 0.13.alpha.0. I don't have a checkout.

Ran that command again, got the following, tried `compass watch`: issue is still there.

```
Successfully installed compass-0.13.alpha.0
1 gem installed
Installing ri documentation for compass-0.13.alpha.0...
Installing RDoc documentation for compass-0.13.alpha.0...
```

**Comment by ARNHOE** [comment] 2013-08-10 15:41
Still seems to be present in 0.12, I was stupid enough to get a PSD file in there named as PNG and Ruby started using 12GB of RAM.

**Comment by scottdavis** [comment] 2013-08-10 17:48
More importantly why would a psd be renamed a png. This should be fixed in the alpha but if its not ill look into it again

**Comment by ARNHOE** [comment] 2013-08-10 17:50
Well as I implied I was stupid enough to get a PSD file renamed to PNG, obviously I didn't knew at the time I did it :P But it was pretty crazy that my pc started using 12GB shortly after compling.

**Comment by henrahmagix** [comment] 2013-08-11 14:13
I wonder if this will also happen with Fireworks PNGs.

**Comment by wvanbergen** [comment] 2013-08-11 15:25
Any file that is given to ChunkyPNG that does not start with the PNG header, will raise an exception as soon as you start reading it. So this would include fireworks files.

My best guess of the problem is that the error handling logic in compass somehow does not properly clean up the allocated memory, and it keeps on trying to load the same file for some reason, eventually draining all memory in the system.

**Comment by cecchi** [comment] 2013-08-15 05:48
I'm having this issue as well... Not sure if I just saved from photoshop as a PSD with a PNG extension, or what, but I'm also seeing massive amounts of memory being eaten up due to a corrupt image. If it's any use, here's the offending file: https://f.cloud.github.com/assets/1663781/967219/0d43bb78-056e-11e3-9c6c-d34d4e2a45db.png (I'm now noticing that Chrome isn't displaying the image correctly either)

This is happening for me in both the stable and most recent alpha releases.

**Comment by kanduvisla** [comment] 2013-09-04 08:36
I had the same issue today. Accidentally saved a PSD with a PNG extension, and the next thing I know compass was hanging in an infinite loop eating op all my memory. running a `$ file --mimetype *` in my images directories revealed which file was the troublemaker. Luckily i found this thread not too late because I don't know what was happening.

Perhaps matching extension with mime-type could prevent this behavior in the future?

**Comment by henrrrik** [comment] 2014-10-09 09:46
We got bitten by this today. Very confusing when Ruby suddenly ate 5+ GB of RAM. A couple of JPEGs hade been named .png by mistake.

**Comment by webpapaya** [comment] 2014-12-04 16:20
just came across the same issue checking the mimetype could solve this issue

**Comment by foxx** [comment] 2014-12-16 16:57
Just had this same problem, thank you to @kanduvisla for the heads up!

```
$ compass watch
>>> Compass is watching for changes. Press Ctrl-C to Stop.
   create images/artwork-s39dab31b3a.png
NoMemoryError on line ["87"] of /home/vagrant/.rvm/gems/ruby-2.1.3/gems/chunky_png-1.3.3/lib/chunky_png/canvas.rb: failed to allocate memory
Run with --trace to see the full backtrace

$ find images/ -iname '*.png' -exec file '{}' \;
images/cc/cc-48px.png: JPEG image data, EXIF standard
```

Could a core dev speculate on a suitable fix? Perhaps just a simple mime check for now?

**Closed as completed** 2017-02-18 05:02 UTC
Labels: sprites, low priority
