### ISSUE TITLE
compass overwrites image_url from sass-rails

### ISSUE THREAD

**Issue by stevenyxu** [Compass/compass#500] opened 2011-07-31 19:17 UTC
I wanted to add compass to an existing Rails 3.1.0.rc5 app that I have. I added the gem to the Gemfile, and used [Ken Collins'](http://metaskills.net/2011/07/29/use-compass-sass-framework-files-with-the-rails-3.1.0.rc5-asset-pipeline/) fix to get the asset pipeline to recognize the compass framework stylesheets.

However, in the process of doing so, compass seemed to overwrite the recently-introduced image_url helper from sass-rails, which would break the links to precompiled assets in the production environment (it would link to /assets/my.png?12345 rather than /assets/my-12345.png)

**Comment by scottdavis** [comment] 2011-08-02 05:59
this is a known issue and chris is "working on it"

**Comment by spohlenz** [comment] 2011-08-05 04:56
If it's of any help, requiring `compass` before `sass-rails` seems to work around the issue for me.

**Comment by stevenyxu** [comment] 2011-08-05 04:57
Indeed; sass-rails just overwrites the method. Thanks for the suggestion in
any case. Here's hoping it saves time for others folks who stumble on this
issue. I'm only sorry I didn't post the solution myself. I don't want to
become "oh I fixed it. nvm"-guy.

**Comment by scottdavis** [comment] 2011-08-06 21:19
the issue is that compass and sass-rails image_url helpers take different arguments. compass needs to be able to detect if sass-rails is loaded and alias the functions

**Comment by huerlisi** [comment] 2011-08-07 19:19
@spohlenz and how do you achieve `compass` being required before `sass-rails`? Switching lines in `Gemfile` didn't help, adding an initializer requiring them didn't work out, either.

**Comment by spohlenz** [comment] 2011-08-07 23:45
@huerlisi an initializer is probably to late in the boot process. Try putting the requires directly in `config/application.rb`.

**Comment by huerlisi** [comment] 2011-08-08 09:30
@spohlenz thanks, works now!

**Comment by johnnym** [comment] 2011-08-08 17:55
@huerlisi, can you explain what you did exactly? I added `require 'compass'` and `require 'sass-rails'` to `config/application.rb`, but it seems that `image-url` still isn't being overridden by sass-rails.

**Comment by huerlisi** [comment] 2011-08-08 18:01
@johnnym, see https://github.com/huerlisi/bookyt/blob/rails3.1/config/application.rb

**Comment by huerlisi** [comment] 2011-08-08 18:05
@johnnym, just realizing that I had to play a bit with `rake assets:clean` and `rake tmp:clear` to get the stylesheet actually rebuilt.

**Comment by johnnym** [comment] 2011-08-08 18:25
Thanks! The cache was the problem. I would have expected it to have been rebuilt automatically since I changed all the `asset-url`'s I was using to `image-url`, but clearing it worked.

**Comment by scottdavis** [comment] 2011-08-09 15:39
Just to warn you all the above solution is not the correct one it may make it work but the compass and sass-rails helpers take different arguments so down the line once this is fixed you will have to refactor.

https://github.com/rails/sass-rails/blob/master/lib/sass/rails/helpers.rb#L13
https://github.com/chriseppstein/compass/blob/master/lib/compass/sass_extensions/functions/urls.rb#L51

**Comment by dfischer** [comment] 2011-08-25 16:23
Any updates on this issue?

**Comment by scottdavis** [comment] 2011-08-25 16:29
Chris wants to do a alpha this week I think

**Comment by alanhogan** [comment] 2011-08-25 19:10
See also: #519. Probably the same issue, but none of the fixes in this thread have worked for me.

**Comment by stevenyxu** [comment] 2011-08-28 18:20
For the folks who need a fix "yesterday", I can still manage to get around the issue (in what I hope is a forwards-compatible way) by using an ERB stylesheet instead. So, I still have the old included stylesheet:

```
.fancy-list {
  li {
    &.linked {
      background-image: image-url('right-arrow.png');
    }
  }
}
```

But then, I've just added a line to "application.css.scss.erb" (rename if necessary):

```
.fancy-list li.linked {
  background-image: url(<%= image_path("right-arrow.png") %>);
}
```

In some future point when this gets fixed, I can remove the line from application.css or even just leave it as is and it should work.

**Comment by aaronchi** [comment] 2011-08-31 15:26
works more simply with

```
.fancy-list li.linked {
  background-image: url(image_path("right-arrow.png"));
}
```

only the image_url function seems to be affected

**Comment by scottdavis** [comment] 2011-09-02 17:38
this should be fixed in the current alpha

**Closed as completed by scottdavis** 2011-09-02 17:38 UTC
