### ISSUE TITLE
Update unprefixed gradients

### ISSUE THREAD

**Issue by jaromero** [Compass/compass#982] opened 2012-08-03 21:48 UTC
Apparently, [Firefox 16 and higher](http://caniuse.com/css-gradients) support unprefixed linear and radial gradients, with the notation outlined in the [Candidate Recommendation](http://www.w3.org/TR/2012/CR-css3-images-20120417/#gradients). but FF16+ also still supports the previous -moz syntax.

However, compass still produces the old unprefixed syntax, which causes FF16+ to render the wrong gradient. FF15 and earlier understand the generated -moz background and apply it correctly. In fact, FF16+ also does this, but then it parses the final unprefixed background, and since the syntax has changed, the resulting gradient is different.

I've built a [quick test on codepen](http://codepen.io/jaromero/pen/toDmh) to try to demonstrate this. FF15 and earlier and webkit render the first gradient properly (they don't understand the unprefixed background yet, so they parse the one they know), and don't render the second one (because of the 'at' which breaks it).

On the other hand FF16+ renders the first gradient wrong (when it falls down to unprefixed, its syntax implies an ellipse as per the candidate recommendation), and the second one is rendered correctly.

The workaround I've been applying in this case is to simply use the background mixin with the old gradient syntax, and then a single rule with the updated unprefixed syntax to override the compass-generated one. My ideal fix though, would be to update compass itself so it would generate the correct, updated unprefixed syntax at all times, but I'm afraid I don't know enough ruby yet to fix it myself.

Now, as far as I can tell, only FF16+ and IE10 support unprefixed gradients so far, so if this gets updated nothing should break. Is this correct? Is this a feasible change?

**Comment by chriseppstein** [comment] 2012-08-03 23:24
Duplicate of #965.

**Closed as completed by chriseppstein** 2012-08-03 23:25 UTC
