### ISSUE TITLE
Compile File to import not found but it is there

### ISSUE THREAD

**Issue by gastonmorixe** [Compass/compass#1453] opened 2013-11-25 00:35 UTC
I am using Compass 0.12.2 (Alnilam) with a rails 4 project.

https://gist.github.com/imton/c15c483ed4059249689e

Compile dies at `@import "./common/global"`

But folder is there and global.css.sass is there too.

In fact, rails compiles/links them successfully. 

Ideas?

**Comment by lolmaus** [comment] 2013-11-25 00:43
Can you please reduce your project to as few files and code necessary as required to reproduce the problem, and post it on Github as a project, so that files/folders structure is maintained, and the problem can easily be reproduced by running `bundle && bundle exec compass compile`?

**Comment by gastonmorixe** [comment] 2013-11-25 01:13
@lolmaus please, give it a try https://github.com/imton/compass_test

**Comment by gastonmorixe** [comment] 2013-11-25 01:14
As soon as you do `bundle exec compass compile` , it says

``` log
    error app/assets/stylesheets/application.css.sass (Line 18: File to import not found or unreadable: ./common/base.
Load paths:
  /Users/gaston/Sites/compass_test/app/assets/stylesheets
  /Users/gaston/.rvm/gems/ruby-2.0.0-p247/gems/compass-0.12.2/frameworks/blueprint/stylesheets
  /Users/gaston/.rvm/gems/ruby-2.0.0-p247/gems/compass-0.12.2/frameworks/compass/stylesheets
  /Users/gaston/.rvm/gems/ruby-2.0.0-p247/bundler/gems/bootstrap-sass-efab96f854dc/vendor/assets/stylesheets
  /Users/gaston/.rvm/gems/ruby-2.0.0-p247/gems/animation-0.1.alpha.3/stylesheets
  Compass::SpriteImporter
  /Users/gaston/.rvm/gems/ruby-2.0.0-p247/bundler/gems/bootstrap-sass-efab96f854dc/vendor/assets/stylesheets)
identical public/assets/application.css
unchanged app/assets/stylesheets/common/base.css.sass
```

**Comment by gastonmorixe** [comment] 2013-11-25 01:25
I have pushed a new commit just now. You can check `rails server` and you will be able to see in the root the background color red.

If you try to compile under compass it will throw the error mentioned. 

Hope it helps, I didn't find anything related to this.

Thanks!
Ton

**Comment by lolmaus** [comment] 2013-11-25 02:00
According to official [documentation](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#import) for `@import`, _If there is no extension, Sass will try to find a file with that name and the .scss or .sass extension and import it._

When you do `@import "./common/base`, Sass searches for `base.sass` and `base.scss`, and your file is named `base.css.sass`.

So change `@import "./common/base"` to `@import "./common/base.css"` and you're good to go.

Also, you might want to rename `base.css.sass` into `_base.css.sass`, so that a separate stylesheet is not produced.

**Comment by gastonmorixe** [comment] 2013-11-25 02:58
@lolmaus Finally! I realized that a minute before you commented. I've updated the repo with the solution working, also it integrates guard-livereload which was my first motive for making this work.

Please, there is a bug that to use `project_type = :rails` it is needed to include in the gemfile of a rails4 app the assets group which is obsoleted from rails4 and on.

Also, when using guard-livereload and running `bundle exec guard -i` I couldn't find a workaround to get compass get `project_type = :rails`. Even with the groups assets hack, it does not work and fires 

``` log
00:40:49 - INFO - Guard is using TerminalTitle to send notifications.
00:40:49 - ERROR - Guard::Compass failed to achieve its <start>, exception was:
> [#0B05B980D203] LoadError: cannot load such file -- compass-rail
> [#0B05B980D203] /Users/gaston/.rvm/gems/ruby-2.0.0-p247/gems/compass-0.12.2/lib/compass/configuration/data.rb:161:in `require'
> [#0B05B980D203] /Users/gaston/.rvm/gems/ruby-2.0.0-p247/gems/compass-0.12.2/lib/compass/configuration/data.rb:161:in `require'
```

I am forced to delete it and let the compass.rb to be 

``` ruby
require 'bootstrap-sass'
require 'animation'

http_path = "/"
css_dir = "app/assets/stylesheets"
sass_dir = "app/assets/stylesheets"
images_dir = "app/assets/images"
javascripts_dir = "app/assets/javsacript"


preferred_syntax = :sass
```

Should I open another issue?

Thank you so much.
Ton

**Comment by lolmaus** [comment] 2013-11-25 03:12
This just doesn't make sense. Why are you using Grunt for compiling Sass in a Rails project that supports Sass and Compass natively? Why are you posting you Grunt hardships into the Compass bug tracker? Why are you not using [grunt-contrib-compass](https://github.com/gruntjs/grunt-contrib-compass)?

**Comment by gastonmorixe** [comment] 2013-11-25 03:50
@lolmaus Because a lot of people wants to use https://github.com/guard/guard-livereload. It is not a problem of who complies but for what. Livereload allows you to install a browser extension and refreshes modified css's in almost realtime as you save them. There might be alternatives, but I didn't find any other. The project you write I was not aware of, does it support livereload?

**Comment by lolmaus** [comment] 2013-11-25 04:24
What if i tell you that you need neither Guard nor a browser extension to do LiveReload with Rails/Sinatra/Padrino/Middleman? Suddenly, [rack-livereload](https://github.com/johnbintz/rack-livereload)!

The question is that why does this belong to the Compass bug tracker? A lot of people are forced to read this with email notifications.

**Comment by gastonmorixe** [comment] 2013-11-25 04:31
@lolmaus Ok. Thank you so much. I am really, really, really, sorry for spamming people with an email. Btw, this is an issue because the convention used in rails differs from the used in compass, and I didn't know this at the time of opening the issue. It might be a mistake but I had to ask somewhere, because I thought this was a compass bug. You can close it. Thanks again.

```
Sprockets supports both Sass syntaxes. For the original whitespace-sensitive syntax, use the extension .css.sass. For the new SCSS syntax, use the extension .css.scss.
```

**Comment by lolmaus** [comment] 2013-11-25 04:39
> convention used in rails differs from the used in compass

That's because Rails doesn't use the `compass` command line tool. It rather uses the Ruby API of the Sass and Compass libraries.

---

>  but I had to ask somewhere, because I thought this was a compass bug.

Though it's not a requirement from the Compass dev team, consider using StackOverflow.com for resolving such issues. Sass community is pretty active there.

---

> You can close it.

Please close it yourself. I'm not a Compass maintainer so i don't have the permission, but you do have because you're the topicstarter.

---

Good luck!

**Closed as completed** 2013-11-25 04:42 UTC
