### ISSUE TITLE
Why compass have 3 versions on Flebox?

### ISSUE THREAD

**Issue by davesnx** [Compass/compass#2058] opened 2016-02-09 10:47 UTC
Hello guys,

I really appreciate the work that you'r doing, but I found a small issue related on Flexbox stuff, I tryed to read on the documentation.

That the mixin of [flexbox](https://github.com/Compass/compass/blob/d5df161d0df7edc686e576b22412f437dd0590cc/core/stylesheets/compass/css3/_flexbox.scss), why don't apply the 3 versions directly?

**Comment by cimmanon** [comment] 2016-02-28 16:35
Duplicate of https://github.com/Compass/compass/issues/1427

**Closed as completed** 2017-04-24 21:29 UTC
