### ISSUE TITLE
bug darken function "Compass 0.12.4.sourcemaps"

### ISSUE THREAD

**Issue by immagimario** [Compass/compass#1565] opened 2014-02-14 15:52 UTC
$progress-bar-border-color: darken(#fff, 20%) !default;
.color { color:$progress-bar-border-color;}

this is normal result is "http://sassmeister.com/": .color {color: #cccccc;}

But in our version of compass, the darken function print this color: #ff9999;

I ask your help to resolve this bug

Thanks

**Comment by lolmaus** [comment] 2014-02-14 19:49
We aee unable to help unless you assemble a minimal project demonstrating the bug and share it via Github. Please check in Gemfile and Gemfile.lock.

**Comment by immagimario** [comment] 2014-02-24 11:07
Hi Lolmaus
thanks for your disponibility

in our project we don't use bundler
but use only installation through of rubyinstaller-2.0.0-p353.exe and with gems of:

gem install sass
Sass 3.3.0.rc.2 (Maptastic Maple

gem install compass
Compass 0.12.4.sourcemaps (clavery-sourcemaps)
Copyright (c) 2008-2014 Chris Eppstein

All projects are installed on windows 7 64bit

This is an example of code that returns an error (foundation zurb):
$header-font-color: #fff !default;
$subheader-font-color: lighten($header-font-color, 30%);

We use the commands of "Sass & Compass Color Functions"; an example you find here http://jackiebalzer.com/color

After scss code it's compiled it returns pink color "#ff9999", regardless of the commands we use to change the color white

**Comment by lolmaus** [comment] 2014-02-24 11:31
Your problem is unusual and is most likely specific to your environment.

If you want us to help you, you have to assemble a minimal project that contains only content required to reproduce the problem. Then share this project via github.com, so that we can have a look at it.

**Comment by chriseppstein** [comment] 2014-03-08 22:26
I can't reproduce this. Closing.

**Closed as completed by chriseppstein** 2014-03-08 22:26 UTC
