### ISSUE TITLE
How can I compile in the same time create *.png use to retina?

### ISSUE THREAD

**Issue by duncan60** [Compass/compass#1515] opened 2014-01-16 06:32 UTC
On Page: http://compass-style.org/help/tutorials/spriting/

How can I compile in  the same time create .png use to retina?
For example:
scss:

@import "compass/utilities/sprites";
@import "my-icons/*.png";

css:
*{  
        background: url('/images/xxx.png') no-repeat;
        background-image: -webkit-image-set(url('../images/xxx.png') 1x,
                url('../images/xxx@2x.png') 2x) ;
}

**Comment by chriseppstein** [comment] 2014-08-19 00:11
duplicate of #1060.

**Closed as completed by chriseppstein** 2014-08-19 00:11 UTC
