### ISSUE TITLE
config.rb ignored until forced

### ISSUE THREAD

**Issue by ijy** [Compass/compass#300] opened 2011-03-14 21:59 UTC
Changes in the config.rb file appear to be ignored even if the source file (.scss) is newer than the target file (.css). Forcing the issue works but doesn't fix the problem. i.e.

compass compile --force stylesheets

**Comment by scottdavis** [comment] 2011-04-01 19:31
Im not seeing this behavior can you give me some more details like ruby version, compass version, and steps to recreate.
My Findings (from new project):

<pre>
$ compass compile 
create public/stylesheets/ie.css 
create public/stylesheets/print.css 
create public/stylesheets/screen.css 
</pre>

run again

<pre>
$ compass compile 
unchanged app/stylesheets/ie.scss
unchanged app/stylesheets/print.scss
unchanged app/stylesheets/screen.scss
</pre>

change config file

<pre>
$ compass compile 
identical public/stylesheets/ie.css 
identical public/stylesheets/print.css 
identical public/stylesheets/screen.css 
</pre>

run again

<pre>
$ compass compile 
unchanged app/stylesheets/ie.scss
unchanged app/stylesheets/print.scss
unchanged app/stylesheets/screen.scss
</pre>

Change output_style

<pre>
$ compass compile
overwrite public/stylesheets/ie.css 
overwrite public/stylesheets/print.css 
overwrite public/stylesheets/screen.css 
</pre>

**Comment by scottdavis** [comment] 2011-04-01 19:33
Also operating system

**Comment by scottdavis** [comment] 2011-04-02 12:31
can't replicate

**Comment by ijy** [comment] 2011-04-20 16:39
Sorry for the delay in replying. 

Ruby: ruby 1.8.7 (2009-06-12 patchlevel 174) [universal-darwin10.0]
Compass: Compass 0.10.6

As for the steps to re-create, well it's just basically a case of putting the watch on the stylesheets directory, making changes to config.rb which sits inside the stylesheets directory. For example changing output_style from :expanded to :compressed. Refreshing the web page and viewing source of CSS to see the changes. At that point nothing has changed despite the changes in the config.rb file.

Hope this helps but let me know if you need more info and I'll do my best to help.

**Comment by scottdavis** [comment] 2011-04-20 18:27
oh this is in 10.6? try it using 0.11 if you can and see if you have the same issue

**Comment by chriseppstein** [comment] 2011-05-01 17:15
Closing. Pretty sure this is fixed in v0.11. Will reopen if @ijy can still reproduce.

**Comment by ixley** [comment] 2011-05-19 01:36
I'm having this same problem and am updated to v0.11.1
Using 'compass watch my_directory' generates new css files after any changes, but does not recognize changes to the config.rb file until I force compile them like noted above.

**Comment by ixley** [comment] 2011-05-20 23:51
anything else I should check for or info I can provide?

**Comment by scottdavis** [comment] 2011-05-21 02:35
I have run through this a few times see above and I'm not seeing an issue. That being said im not calling you crazy i just don't know what to tell you =\

**Comment by ixley** [comment] 2011-05-25 22:37
fair enough. it's not the worst problem to have. Maybe it'll resolve itself with continued upgrades down the line.

**Comment by chriseppstein** [comment] 2011-05-25 22:44
I don't see any code in the update_project command for this... I thought it was there. It should just be a matter of running:

```
compiler.clean! if compiler.new_config?
```

**Comment by scottdavis** [comment] 2011-05-26 18:44
@ixley, try using this commit see if it fixes the problem

https://github.com/chriseppstein/compass/commit/d080fdddb779d5dc4d56676d664c3fccd11bc724

**Comment by chriseppstein** [comment] 2011-07-03 18:06
closing this as fixed. Please comment if not.

**Comment by ijy** [comment] 2011-07-12 14:04
Sorry for the delay in getting back on this. I've just tried it again having updated to the current latest version of Compass (0.11.5) and the problem is still there.

My stylesheets are all hooked up and style changes are working fine. config.rb is placed in the stylesheets directory. When I cycle output_style through the various formats none of them seem to make a difference. If however I force the issue with 

compass compile --force stylesheets

and refresh the page, view the source, it works with the output compressed (or whatever output style I have selected). This doesn't seem to have changed at all from when I first posted the issue.

**Comment by CaioBianchi** [comment] 2011-07-30 15:10
Having the same issue here! I was playing with it all day yesterday... and out of the blue stopped working!
Compass compiles the css file, but just ignores the config.rb file.

**Comment by Karolined** [comment] 2011-09-01 10:48
Hi, I was looking at this problem today. Downloaded latest of compass, it compiled the css, but was ignoring the settings in my config.rb file. For me this seemed to be caused by running the compass commands from the wrong folder. I was running the compass compile/watch command standing in the folder above the one actually containing the config.rb file.

**Comment by ijy** [comment] 2011-09-01 12:16
Although I'm not quite using the latest version - still on Compass 0.11.5 (Antares). I've just re-tried it every which way I can think of but still no change. I have compass watching in one window which is correctly compiling all the changes to my stylesheets but it's completely ignoring my config.rb file. When just testing now even forcing compile (compass compile) doesn't work. 

I have noticed that it usually takes some time for it to notice any changes in the config.rb file but does seem to get there in the end. For instance I've now just cycled through all output styles and once or twice this command was recognised and obeyed but not it's not paying any notice at all. I may fire things up again tomorrow and it suddenly sees that I've set the output_style to :compressed and it suddenly kicks into action.

I've cleared the .sass-cache directory and I'm even using PHP checking on the stylesheet link in the document head so that it appends the stylesheet with the unique timestamp using query strings so that every time it's updated it should be pulling the new version. Still no change. The randomness has me stumped. It is quite annoying though cause I never know what it's going to go with and if I'm waiting to deploy then I need it compressed and waiting a random amount of time (hours/days/weeks?) for it to notice the settings in config.rb is tedious.

**Comment by CaioBianchi** [comment] 2011-09-07 22:10
The solution that I've found is restarting the "watch" function. it all works fine, perhaps a limitation. =\

**Comment by ijy** [comment] 2011-09-09 08:40
Does that consistently work for you? I can confirm that I've tried stopping and starting the watch as well as watching both the directory containing the config.rb file and the specific stylesheets directory and neither fixes things for me. 

Like I said it seems to always get there in the end but it just seems inconsistent. I've changed my output compression from nested to compressed, stopped the watch, started the watch, saw that my stylesheets were compiled, but alas the output .css files were still nested. config.rb had been ignored. When I forced compile it then did take notice.

**Comment by CaioBianchi** [comment] 2011-09-09 14:18
yes, it works fine! kinda inconvenient and the process kinda sloppy... but it works! I don't think it would be much work to just watch that ruby file for changes.

**Comment by chriseppstein** [comment] 2011-09-09 19:51
Some notes:
1. You _have_ to restart the watcher if the config changes.
2. Compass _should_ run a  "clean" if the config is newer than any existing css files.
3. The --force option exists for just this kind of reason. :)

As seen here, #2 seems to be working for me:

```
$ touch config/compass.rb 
$ bundle exec compass compile
   remove .sass-cache/ 
   remove public/stylesheets/page.css 
   create public/stylesheets/page.css 
```

Are you sure there's a bug?

**Comment by ijy** [comment] 2011-09-10 10:23
Hey Chris,

1) Sometimes it works, sometimes it doesn't
2) _'Should'_ but definitely not always. Actually not very often at all.
3) Probably the most useful command of them all. Thank the lord for manual overrides :)

As for a _'bug'_, well that depends purely on the intended operations of Compass along with the definition for bug. With --force there is an alternative way so it's not end of the world stuff but whenever there's inconsistencies and a lot of 'should's it generally points to something being amiss. I'd certainly prefer it to be consistent but like I said, as long as I can force it to work then it's not killer.

**Comment by chriseppstein** [comment] 2011-09-11 21:00
@ijy I need you to provide steps to reproduce that a change to the config doesn't cause a clean on the next compilation. I showed you the steps I was taking. Do those steps work or not for you?

**Comment by scottdavis** [comment] 2012-03-15 18:49
closing this since no updates in 6 months

**Closed as completed by scottdavis** 2012-03-15 18:49 UTC
Labels: feature request, bug, compass core, v0.10, documentation, needs patch, Test after listen integration

**Comment by chriseppstein** [comment] 2012-03-15 19:11
Compass now does an automatic clean when compiling or starting the watcher if the config file is newer than any of the generated css files.

**Comment by josipf** [comment] 2012-04-18 13:19
still having troubles with this issue on win7. Chris' solution didn't work for me.

**Comment by ethanbeyer** [comment] 2014-03-07 02:42
I'm having this issue - I'll try to be as detailed as possible so that this is in some way reproducible.
I just wiped my entire computer yesterday and reinstalled everything from scratch.

Ruby: ruby 2.0.0p247 (2013-06-27 revision 41674) [universal.x86_64-darwin13]
Compass: Compass 0.12.3 (Alnilam)

I'm working on a site locally with MAMP. Here's the directory structure pictured alongside my config.rb file.
![screen shot 2014-03-06 at 21 37 26](https://f.cloud.github.com/assets/6864684/2353438/79e8493c-a5a1-11e3-9411-d1a682219215.png)

What happens is I go to _themes/embers and I run "compass watch" and what results are whatever settings have been cached before, or...something. If I run "compass init" it tosses ie.scss, print.scss and screen.scss in the /scss directory and the same three files ending in .css in the /css folder.
If I run "compass compile --force", the settings in my config.rb file are respected - but the benefit of watch, as I understand it, is that my changes will be reflected on the fly, as I make changes to the scss and save them. The style changes are compiled correctly, but always with all the line comments, no matter how many times I run "--force".

Plz halp!

**Comment by ethanbeyer** [comment] 2014-03-07 02:44
Is there a way to simply tell compass, similar to bash, to just source a file? Something like "compass reload config.rb"?

**Comment by mm-tom** [comment] 2014-03-21 21:17
I don't have this issue, but just curious - does it still occur if you tell it the path to your config file? e.g:

```
compass watch -c ./compass/config.rb
```

**Comment by chriseppstein** [comment] 2014-03-21 21:22
Compass requires you to restart the watcher if you change your configuration. If it detects any css files are older than the configuration file, it runs a `compass clean` before the first compile.

**Comment by spilliams** [comment] 2015-07-22 00:05
I just upgraded from ruby 2.0.0 to 2.2.2 (via rvm) and had to gem install compass again. When I run compass now it ignores my config.rb file (even if I `compass watch . -c config.rb`). Specifically it writes css files to the same directory that scss files are in (where config.rb denotes `css_dir = "public/stylesheets"` and `sass_dir = "public/scss"`).
