### ISSUE TITLE
compiler.rb: wrong number of arguments (3 for 2)

### ISSUE THREAD

**Issue by piouPiouM** [Compass/compass#306] opened 2011-03-25 08:41 UTC
The compilation breaks with Compass 0.11.beta.4.

```
$ compass compile --config scss/theme.rb --trace
ArgumentError on line 105 of /Library/Ruby/Gems/1.8/gems/compass-0.11.beta.4/lib/compass/compiler.rb: wrong number of arguments (3 for 2)
  /Library/Ruby/Gems/1.8/gems/compass-0.11.beta.4/lib/compass/compiler.rb:105:in `compile_if_required'
  /Library/Ruby/Gems/1.8/gems/compass-0.11.beta.4/lib/compass/compiler.rb:92:in `run'
  /Library/Ruby/Gems/1.8/gems/compass-0.11.beta.4/lib/compass/compiler.rb:90:in `each'
  /Library/Ruby/Gems/1.8/gems/compass-0.11.beta.4/lib/compass/compiler.rb:90:in `run'
  /Library/Ruby/Gems/1.8/gems/compass-0.11.beta.4/lib/compass/compiler.rb:113:in `timed'
  /Library/Ruby/Gems/1.8/gems/compass-0.11.beta.4/lib/compass/compiler.rb:89:in `run'
  /Library/Ruby/Gems/1.8/gems/compass-0.11.beta.4/lib/compass/commands/update_project.rb:36:in `perform'
  /Library/Ruby/Gems/1.8/gems/compass-0.11.beta.4/lib/compass/commands/base.rb:18:in `execute'
  /Library/Ruby/Gems/1.8/gems/compass-0.11.beta.4/lib/compass/commands/project_base.rb:19:in `execute'
  /Library/Ruby/Gems/1.8/gems/compass-0.11.beta.4/lib/compass/exec/sub_command_ui.rb:43:in `perform!'
  /Library/Ruby/Gems/1.8/gems/compass-0.11.beta.4/lib/compass/exec/sub_command_ui.rb:15:in `run!'
  /Library/Ruby/Gems/1.8/gems/compass-0.11.beta.4/bin/compass:25
  /Library/Ruby/Gems/1.8/gems/compass-0.11.beta.4/bin/compass:39:in `call'
  /Library/Ruby/Gems/1.8/gems/compass-0.11.beta.4/bin/compass:39
  /usr/bin/compass:19:in `load'
  /usr/bin/compass:19
```

**Comment by chriseppstein** [comment] 2011-03-25 15:08
That error doesn't make much sense. The method clearly accepts three
arguments. Are you monkey patching compass or maybe you have a plugin that
does?

**Comment by piouPiouM** [comment] 2011-03-25 15:36
I had to install the compass-growl gem (via rubygems).
Before that I worked with version 0.10.6 (which I returned).

**Comment by chriseppstein** [comment] 2011-03-25 16:20
Can you please tell me more about your environment? How do you compile your stylesheets? do you use a ruby app? What other compass plugins do you have?

**Comment by chriseppstein** [comment] 2011-03-25 16:24
Can you please tell me more about your environment? How do you compile your stylesheets? do you use a ruby app? What other compass plugins do you have?

**Comment by piouPiouM** [comment] 2011-03-25 16:35
I compiles my stylesheets via the compass comand line and I only use the lemonade plugin (by writing this line, I wonder if the inclusion of lemonade is not the fault).

More information about my environment:

```
$ uname -a
Darwin ppm-cal.local 10.6.0 Darwin Kernel Version 10.6.0: Wed Nov 10 18:13:17 PST 2010; root:xnu-1504.9.26~3/RELEASE_I386 i386
$ ruby --version
ruby 1.8.7 (2009-06-12 patchlevel 174) [universal-darwin10.0]
$ gem --version
1.3.7
```

**Comment by chriseppstein** [comment] 2011-03-25 18:10
What version of Sass do you have?

**Comment by piouPiouM** [comment] 2011-03-25 20:44
Sass 3.1.0.alpha.252.

Note: iIf I comment in my config file the line `require "lemonade"` the compilation starts.

**Comment by johnthedebs** [comment] 2011-03-27 21:25
I'm seeing this same issue with Compass 0.11.beta.5. I also have `require "lemonade"` in my config.rb and compilation starts (then fails for other reasons) when I comment that out.

The traceback:

```
$ compass compile --trace
ArgumentError on line 105 of /Library/Ruby/Gems/1.8/gems/compass-0.11.beta.5/lib/compass/compiler.rb: wrong number of arguments (3 for 2)
  /Library/Ruby/Gems/1.8/gems/compass-0.11.beta.5/lib/compass/compiler.rb:105:in `compile_if_required'
  /Library/Ruby/Gems/1.8/gems/compass-0.11.beta.5/lib/compass/compiler.rb:92:in `run'
  /Library/Ruby/Gems/1.8/gems/compass-0.11.beta.5/lib/compass/compiler.rb:90:in `each'
  /Library/Ruby/Gems/1.8/gems/compass-0.11.beta.5/lib/compass/compiler.rb:90:in `run'
  /Library/Ruby/Gems/1.8/gems/compass-0.11.beta.5/lib/compass/compiler.rb:113:in `timed'
  /Library/Ruby/Gems/1.8/gems/compass-0.11.beta.5/lib/compass/compiler.rb:89:in `run'
  /Library/Ruby/Gems/1.8/gems/compass-0.11.beta.5/lib/compass/commands/update_project.rb:36:in `perform'
  /Library/Ruby/Gems/1.8/gems/compass-0.11.beta.5/lib/compass/commands/base.rb:18:in `execute'
  /Library/Ruby/Gems/1.8/gems/compass-0.11.beta.5/lib/compass/commands/project_base.rb:19:in `execute'
  /Library/Ruby/Gems/1.8/gems/compass-0.11.beta.5/lib/compass/exec/sub_command_ui.rb:43:in `perform!'
  /Library/Ruby/Gems/1.8/gems/compass-0.11.beta.5/lib/compass/exec/sub_command_ui.rb:15:in `run!'
  /Library/Ruby/Gems/1.8/gems/compass-0.11.beta.5/bin/compass:25
  /Library/Ruby/Gems/1.8/gems/compass-0.11.beta.5/bin/compass:39:in `call'
  /Library/Ruby/Gems/1.8/gems/compass-0.11.beta.5/bin/compass:39
  /usr/bin/compass:19:in `load'
  /usr/bin/compass:19
```

My environment info:

```
$ uname -a
Darwin Johns-MBP.local 10.7.0 Darwin Kernel Version 10.7.0: Sat Jan 29 15:17:16 PST 2011; root:xnu-1504.9.37~1/RELEASE_I386 i386
$ ruby --version
ruby 1.8.7 (2009-06-12 patchlevel 174) [universal-darwin10.0]
$ gem --version
1.6.2
```

(Despite it saying Kernel Version 10.7.0, I'm on OS X 10.6.7)

Let me know if any other info would be helpful.

**Comment by chriseppstein** [comment] 2011-03-28 04:12
What version of Sass do you have?

**Comment by johnthedebs** [comment] 2011-03-28 04:15
```
$ sass --version
Sass 3.1.0.alpha.249 (Bleeding Edge)
```

**Comment by chriseppstein** [comment] 2011-04-03 23:31
Ok. The issue is that the stable release of lemonade gem overrides some compass APIs. The [beta release](https://rubygems.org/gems/lemonade/versions/1.0.0.beta.1) of lemonade doesn't have this issue, but it doesn't really work with compass anymore due to dependency conflicts. Since the functionality of lemonade is now merged with compass, I am going to close this issue. Please use [compass sprites](http://beta.compass-style.org/help/tutorials/spriting/) now. It's possible that @hagenburger will want to make some changes to lemonade so that it can coexist with compass v0.11, I'll let him decide what to do about that.

**Closed as completed by chriseppstein** 2011-04-03 23:31 UTC
Labels: feature request, bug, compass core, documentation, needs patch
