### ISSUE TITLE
Compass's version of blueprint grids does not seem to work with html5 block elements

### ISSUE THREAD

**Issue by sohara** [Compass/compass#197] opened 2010-09-22 21:19 UTC
Hi there,
I tried adding @included column(12) to a selector for the <section> element on my page and this doesn't seem to work as it does for a div element. I believe this has been corrected in the blueprint project, but perhaps not in the abstraction of blueprint used by compass?

http://blueprintcss.lighthouseapp.com/projects/15318/tickets/86-html5-block-tags-incompatibility

**Comment by chriseppstein** [comment] 2010-10-11 17:37
dupe of #202

**Closed as completed by chriseppstein** 2010-10-11 17:37 UTC
