### ISSUE TITLE
rails 3.1 asset pipeline exponentially slow with compass

### ISSUE THREAD

**Issue by wakiki** [Compass/compass#516] opened 2011-08-19 11:35 UTC
Using rails 3.1's new way of writing css files, I have about 30 .css.sass.erb files in my /assets/stylesheets directory

each of them uses blueprint and compass mixins like +column(x), so I have to include compass and blueprint at the top of each file. 

The result is that it takes about 2-3 minutes to compile the stylesheet via sprockets the first time, and every time I change any css it takes about 12 seconds to refresh. The issue becomes exponentially worse for every new sass file I put in the directory. 

Trouble is, this is the new rails pattern is it not? 

Am I doing something wrong here? Can anyone help? 

Cheers - Steve

gem 'rails', '3.1.0.rc6'
gem 'haml', '3.1.2'
gem 'haml-rails', '0.3.4' # haml gem doesn't include rails generators by default, so this gem includes it
gem 'sass', '3.1.7'
gem 'sass-rails', "~> 3.1.0.rc.6"

**Comment by wakiki** [comment] 2011-08-19 11:36
Whoops forgot to include compass gem! 

gem 'compass', :git => 'git://github.com/chriseppstein/compass.git', :branch => 'rails31'

**Comment by scottdavis** [comment] 2011-08-19 13:06
rails 31 integration isn't perfect yet and we are working on it keep an eye on the main ticket https://github.com/chriseppstein/compass/issues/337

**Comment by julioprotzek** [comment] 2011-10-05 23:40
The https://github.com/chriseppstein/compass/issues/337 topic was closed but the problem remains.
Any ideas?

**Comment by leehambley** [comment] 2011-11-01 20:48
This is a problem still for me, I'm seeing absolutely insane (2500ms) requests, more than 90% of my request time for a fairly trivial app.

**Comment by scottdavis** [comment] 2011-11-02 02:03
im not having this problem in my rails 3.1.0 app are you using an older version of sass?

**Comment by julioprotzek** [comment] 2011-11-02 04:20
I ended up skiping asset pipeline for this project and compiling sass with `compass watch`. But I was using sass version which comes with Rails 3.1.1 O.o

**Comment by leehambley** [comment] 2011-11-02 08:03
Here's the low-down:

$ bundle show | ack '(?:rails|sass)'
- rails (3.1.0)
- sass (3.1.10)
- sass-rails (3.1.2)

I'm using :compass from @chriseppstein's master.

**Comment by leehambley** [comment] 2011-11-12 11:53
I'm seeing ~14 seconds to compile the following: 

``` text
$ ls -lr ./app/assets/stylesheets/
total 160
-rw-r--r--   1 codebeaker  staff   765B 12 Nov 11:50 screen.css.scss
drwxr-xr-x   3 codebeaker  staff   102B 14 Aug 16:54 admin
-rw-r--r--   1 codebeaker  staff   1.5K  6 Nov 14:14 _typography.scss
-rw-r--r--   1 codebeaker  staff   2.1K 10 Nov 19:36 _tipsy.css
-rw-r--r--   1 codebeaker  staff   2.4K 10 Nov 19:36 _structure.scss
-rw-r--r--   1 codebeaker  staff   1.2K 10 Nov 19:36 _shows.css.scss
-rw-r--r--   1 codebeaker  staff   230B 10 Nov 19:36 _seasons.css.scss
-rw-r--r--   1 codebeaker  staff   7.9K 20 Aug 21:35 _reset.css
-rw-r--r--   1 codebeaker  staff   479B  6 Nov 11:39 _pagination.css.scss
-rw-r--r--   1 codebeaker  staff   566B  6 Nov 11:39 _mixins.scss
-rw-r--r--   1 codebeaker  staff     0B 14 Aug 16:54 _lightbox.scss
-rw-r--r--   1 codebeaker  staff    95B  5 Nov 17:38 _imports.scss
-rw-r--r--   1 codebeaker  staff   438B 10 Nov 19:36 _images.css.scss
-rw-r--r--   1 codebeaker  staff   829B 12 Nov 12:50 _home.css.scss
-rw-r--r--   1 codebeaker  staff   300B 23 Aug 19:39 _header.scss
-rw-r--r--   1 codebeaker  staff   1.3K 10 Nov 19:36 _forms.scss
-rw-r--r--   1 codebeaker  staff   598B 10 Nov 19:36 _footer.css.scss
-rw-r--r--   1 codebeaker  staff   674B 10 Nov 19:36 _flashes.scss
-rw-r--r--   1 codebeaker  staff   418B 10 Nov 19:36 _episodes.css.scss
-rw-r--r--   1 codebeaker  staff   766B  6 Nov 01:10 _colours.scss
-rw-r--r--   1 codebeaker  staff   1.0K  6 Nov 14:25 _buttons.scss
drwxr-xr-x   5 codebeaker  staff   170B 10 Nov 21:05 ..
drwxr-xr-x  23 codebeaker  staff   782B 12 Nov 12:50 .
```

Using: 

``` text
$ cat Gemfile.lock | ack '(?:sass|compass|bour)'
  remote: https://github.com/chriseppstein/compass.git
    compass (0.12.alpha.0.724a5dc)
      sass (~> 3.1)
    bourbon (1.1.0)
      sass (>= 3.1)
    sass (3.1.10)
    sass-rails (3.1.4)
      sass (>= 3.1.4)
  bourbon
  compass!
  sass-rails (~> 3.1)
```

The top of `screen.css.scss` looks like:

``` scss
30px @ 1:1.618

 Read More:
 http://modularscale.com/scale/?px1=16&px2=30&ra1=1.618&ra2=0

----------------------*/

@import 'imports';

@import 'reset';
@import 'typography';
@import 'structure';
@import 'pagination';

@import 'flashes';
@import 'forms';
@import 'header';
@import 'footer';

@import 'home';
@import 'images';
@import 'shows';
@import 'seasons';
@import 'episodes';
@import 'tipsy';
```

The `import.scss` looks like:

``` scss
@import 'compass';
@import 'bourbon';

@import 'mixins';
@import 'colours';
@import 'buttons';
```

**Comment by whather** [comment] 2011-11-28 22:44
I'm also seeing really long compile times with compass and Rails 3.1. Removing compass, compile times are normal and fast. Have any improvements been made recently?

**Comment by scottdavis** [comment] 2011-11-28 23:36
latest version of sass?

**Comment by whather** [comment] 2011-11-28 23:39
Yeah:

Using sass-rails (3.1.5)
Using sass (3.1.11)
Using compass (0.12.alpha.2)

**Comment by scottdavis** [comment] 2011-11-28 23:49
sprites?

**Comment by whather** [comment] 2011-11-28 23:52
No sprites

**Comment by leehambley** [comment] 2011-11-29 08:20
( +1 no sprites, for me either ) - seeing compile times of the previous
example that I posted in the region of 8 seconds.

It \* definitely\* helped (~30%?) to kick out the initializer hack as
described here:
http://metaskills.net/2011/05/18/use-compass-sass-framework-files-with-the-rails-3.1-asset-pipeline/-
I notice that he has updated the article recently to recommend _not_
following his instructions.

**Comment by olivierlacan** [comment] 2011-12-06 22:23
I was seeing this behavior without Sprites (https://github.com/rails/sass-rails/issues/36).
I do not have an initializer hack.

Removing all mixins from my stylesheets reduces the slow compile issue.
This issue has always been correlated with mixins (or the arguments passed to mixins).

Updating to Sass 3.1.11 and Compass 0.12.alpha.2 didn't change a thing.

Also see https://github.com/rails/sass-rails/issues/36

**Comment by scottdavis** [comment] 2011-12-06 22:25
chris is looking into this i think he narrowed it down to a GC issue

**Comment by chriseppstein** [comment] 2011-12-06 22:30
I don't fully understand the issue. could really use some help profiling this and finding the culprit(s). The Sass::Rails/Sprockets importer is also slow -- I can get a significant speedup (~30%) by placing it last on the loadpath.

I don't understand why GC would be so much worse in a rails process than stand alone.

**Comment by whather** [comment] 2011-12-07 01:16
I use a bunch of mixins and imports and sometimes see sass compilation times exceeding 2.5 minutes. Please let me know if you make any improvements. Thanks!

**Comment by jtmkrueger** [comment] 2011-12-07 19:41
+1 for this.  Were using a bunch of mixins and imports and seeing times up to 25 seconds.

**Comment by leehambley** [comment] 2011-12-07 20:09
Asto the hint about GC, any easy ways to disable GC for one localized module, or can the OP with that idea share his benchmarking code so we can reproduce?

**Comment by Papipo** [comment] 2011-12-15 16:43
How is this coming along? I can't work on my laptop, each time I need to change my stylesheets I have to wait ages -_-

**Comment by DanielWright** [comment] 2011-12-15 16:48
YMMV, but I've found that selectively importing specific Compass modules (e.g. `@import compass/css3/inline-block`), rather than simply `@import compass`, dramatically improves compilation time.

**Comment by scottdavis** [comment] 2011-12-15 18:27
maybe the sass-rails importer is being slow ill have some time this weekend to slam my face into this

**Comment by leehambley** [comment] 2011-12-15 18:35
> to slam my face into this

Nice to know I'm not the only one that feels like maintaining open source isn't good for my health of beauty :-D 

## 

Lee Hambley
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)

**Comment by scottdavis** [comment] 2011-12-15 18:45
Its not the maintaining part (since I use it) its mostly having to integrate with other open source applications that makes me want to burn things

**Comment by whather** [comment] 2011-12-15 18:52
Scott, yeah I have a hunch it's the sass-rails importer. Looking forward to what you find over the weekend!

**Comment by scottdavis** [comment] 2011-12-15 20:20
anyone that wants to help out buy running a https://github.com/tmm1/perftools.rb on your rails app and emailing me the graph to me@sdavis.info would be helpful

**Comment by Papipo** [comment] 2011-12-15 23:39
It seems that the first request to my rails application stylesheet runs pretty fast. Then I make any change to my scss manifest file, or any of the partials it imports, and the slow party begins.

**Comment by scottdavis** [comment] 2011-12-15 23:46
can you run a perftools for me for both runs?

**Comment by Papipo** [comment] 2011-12-16 00:18
The first one is so fast that I don't get stuff to print in the graph. I can send you the second one.

**Comment by Papipo** [comment] 2011-12-16 00:22
Sent.

**Comment by scottdavis** [comment] 2011-12-16 00:36
thanks

**Comment by scottdavis** [comment] 2011-12-16 02:29
Do all of you have haml installed?

**Comment by whather** [comment] 2011-12-16 02:29
Yep

**Comment by scottdavis** [comment] 2011-12-16 02:33
haml seems to be secretly loading the Sass rack middleware try this in your application.rb and see if it helps

<pre>
config.after_initialize do |c|
  c.middleware.delete(Sass::Plugin::Rack)
end
</pre>

**Comment by scottdavis** [comment] 2011-12-16 02:36
https://github.com/nex3/haml/issues/472

**Comment by scottdavis** [comment] 2011-12-16 02:55
also you can just gist the text perfs
https://gist.github.com/d2ee08504d4c0c77c2a1#L145

**Comment by scottdavis** [comment] 2011-12-16 03:37
i get about a 100ms speed up doing this

<pre>

    config.after_initialize do |c|
      #c.middleware.delete(Sass::Plugin::Rack)

      class Sass::Plugin::Rack
        def call(env)
          puts "moving on"
          @app.call(env)
        end
      end

    end
</pre>

**Comment by scottdavis** [comment] 2011-12-16 03:38
another perf from my app: https://gist.github.com/1484335

**Comment by scottdavis** [comment] 2011-12-16 03:51
the Sass::Plugin::Rack call isn't the problem here and removing it is marginal performance boots at best since if it runs it just warms the sass-cache and then it hits the asset pipeline it just renders the cache out the pipeline

**Comment by scottdavis** [comment] 2011-12-16 04:09
@Papipo whats in your Gemfile my callgraphs are looking very different

mine:
http://dl.dropbox.com/u/177158/callgrinds/newscenter.gif
http://dl.dropbox.com/u/177158/callgrinds/newscenter-1.gif

yours:
http://dl.dropbox.com/u/177158/callgrinds/application.css.gif

**Comment by scottdavis** [comment] 2011-12-16 04:13
in fact it looks like most of the time in yours it spends a lot time rescuing from file system objects that don't exist .. are you sure you import statements are correct and your cache_dir is set properly?

you are not using the `//= require` directives in sprockets are you?

it seems yours is getting caught up in here https://github.com/sstephenson/hike/blob/master/lib/hike/index.rb#L81

im curious to see what others have in their graphs

**Comment by scottdavis** [comment] 2011-12-16 08:25
http://dl.dropbox.com/u/177158/callgrinds/admin.gif

**Comment by Papipo** [comment] 2011-12-16 09:26
Well, as I said, the first request is very fast. Then I just comment one partial import an it becomes extremely slow.

in the sprockets part, I just require_self in the manifest file, the rest are imports of blueprint and sass mixins and my own partials. I don't think there is nothing wrong with my paths, I tried with just one partial and several compass/blueprint imports and it's sloooow.

**Comment by leehambley** [comment] 2011-12-16 09:44
- Graph: http://cl.ly/1R3Z3v2Y1h3F0H2g3z1W
- Text: https://gist.github.com/85398f73264f0c0c2a2a

The profile options were `/assets/screen.css?times=three` using the Rack perftools.rb gem.

**Comment by Papipo** [comment] 2011-12-16 15:53
Well, I think that that first fast request is not exactly correct. It might have cached the stylesheet from a previous development session. Each time I modify any of my scss files, then it gets really slow, no matter if it's the first css request to the server.

And I have detected something weird: my append-bottom calls don't appear in the compiled stylesheet, I have to add margin-bottom instead. It has nothing to do with the slowness I guess, but who knows :D

**Comment by scottdavis** [comment] 2011-12-16 16:29
@leehambley i think you profiled a cache call remove tmp/cache and run it again

**Comment by Papipo** [comment] 2011-12-16 16:33
Well I created a test.scss file with a single compass import (@import "compass/typography/lists";) and it took 15 seconds to process it.

**Comment by scottdavis** [comment] 2011-12-16 16:33
im seing on average about 4000 ms in my app

**Comment by leehambley** [comment] 2011-12-16 16:44
@scottdavis I have no `./tmp/cache` - and my app is still showing:

``` log
Started GET "/assets/screen.css" for 127.0.0.1 at 2011-12-16 17:43:15 +0100
Served asset /screen.css - 304 Not Modified (5ms)
```

Also, the `.css` file isn't existing anywhere in the project, do I have to profile this in production mode? (or could I be using something out of date?)

**Comment by scottdavis** [comment] 2011-12-16 16:51
im not sure you should have a sass-cache someplace

**Comment by Papipo** [comment] 2011-12-16 16:59
@leehambley are you using a different cache config in your app than the default one?

**Comment by leehambley** [comment] 2011-12-16 17:01
@Papipo not in development mode, there's a `./tmp/cache/sass/` but it's empty. (still investigating here!)

**Comment by stoplion** [comment] 2011-12-16 17:26
Seeing 2–5 min load times.

rails 3.1.3
sass 3.1
compass 0.11.1
sass-rails 3.1.5
sprockets 2.0.3

**Comment by leehambley** [comment] 2011-12-16 18:01
Can I suggest (I don't have the time unfortunately) but could someone open-source their CSS for the purposes of debugging this? Maybe we could run this on some different implementations of Ruby, and different system profiles, and see if we can pool our results..

## 

Lee Hambley
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)

**Comment by Papipo** [comment] 2011-12-17 00:34
@leehambley there is no need for that, I am getting extremely slow speeds with a simple @import

**Comment by ErwinM** [comment] 2011-12-18 16:00
We recently kicked compass out of our app because of this issue. Real shame, but people were going mad in development.

**Comment by scottdavis** [comment] 2011-12-18 17:10
Can someone open source something really slow or create an example my app has about 200 imports and while it's a bit slow it's only about 4500ms I'm not seeing this problem of several minutes it maybe a circular import?

**Comment by Papipo** [comment] 2011-12-18 22:09
Not in my case, I have tried very simple setups. Gonna install another ruby version or something, this is driving me nuts.

**Comment by Papipo** [comment] 2011-12-18 22:47
I guess this must have something to do with my application setup. Compiling active_admin.css takes 28 seconds here.

**Comment by Papipo** [comment] 2011-12-18 23:28
Please checkout this app https://github.com/Papipo/slow-compass-rails and let me know how much it takes to generate http://localhost:3000/assets/active_admin.css

**Comment by scottdavis** [comment] 2011-12-19 15:36
Compiled active_admin.css  (2307ms)  (pid 91983)

**Comment by Papipo** [comment] 2011-12-19 15:44
Here in a 13" macbook it takes 20 seconds. Is that normal?

**Comment by scottdavis** [comment] 2011-12-19 16:43
I'm on an imac with an i7 and SSD and its taking me 2.30700 seconds

**Comment by Papipo** [comment] 2011-12-19 17:03
Maybe this is just as slow as it's supposed to be. I can bring it down to 12 secs if I import border-radius and opacity separately, but this is just a small example and it sucks a lot -_-

**Comment by olivierlacan** [comment] 2011-12-19 17:20
2011 Core i5 MacBook Air 

```
Compiled active_admin.css  (2420ms)  (pid 44251)
```

But let me tell you, this issue is not that easy to reproduce. I've tried numerous times to create apps to reproduce the problem, in vain. I'd be interested to know how many people have issues with apps that were transitioned from Rails 3.x to Rails 3.1.x

I've also been recently forced to extract Compass from a work project since I was getting 8-10 second compiles at best.

**Comment by Papipo** [comment] 2011-12-19 17:56
This app I posted was created from scratch, and the real application I am working on, has compile times of about 45 secs and it's rails 3.1 from the beginning.

**Comment by Papipo** [comment] 2011-12-19 18:07
Once I get home I am going to test this with a Quadcore iMac, not sure if there it will be manageable just because the CPU is faster. I think that in my laptop I have something that acts as bottleneck, but I don't know what it can be. I even tried switching from rvm to homebrew ruby 1.9.2.

**Comment by scottdavis** [comment] 2011-12-19 18:16
Chris and I talked Some today and this is looking more like a GC issue because of the rails stack overhead the solution for now is to only require what you need

**Comment by Papipo** [comment] 2011-12-19 19:43
Where can I find resoures about interpreting perftools resutls and ruby profiling in general?

**Comment by scottdavis** [comment] 2011-12-19 20:29
The google code wiki for perftools

**Comment by scottdavis** [comment] 2011-12-19 22:44
if you are using `@import "compass"` at the top of your stylesheets you are creating a very heavy IO load for sass to import all those files and parse / cache this on top of the over head from rails/sprockets is being slow I believe. That or there is a circular require and on cacheing issue

**Comment by Papipo** [comment] 2011-12-19 23:44
I think I have found the problem, and why it only affects some people. It seems to affect applications that load many gems which add extra asset search paths. That adds a lot of overhead, and putting the sprockets importer at the end of the load_paths in https://github.com/rails/sass-rails/blob/master/lib/sass/rails/template_handlers.rb#L74 brought my css from > 50secs to only 10.

**Comment by scottdavis** [comment] 2011-12-20 00:46
https://github.com/sstephenson/sprockets/pull/268#issuecomment-3212022

**Comment by Papipo** [comment] 2011-12-20 20:14
Imagine how much overhead all those paths add, that with the sass-rails fix my stylesheets compile faster if I import the whole blueprint and compass instead of separate mixins. Now I brought them down to 4 secs :-)

**Comment by ErwinM** [comment] 2012-01-22 19:03
@papipo how did you achieve your speed up? I am looking at your code link, but I don't get it. However, I would love to get a speed up so I can re-introduce compass in our app..

**Comment by Papipo** [comment] 2012-01-23 13:43
Change this:

```
load_paths.unshift(importer)
```

To this:

```
load_paths << importer
```

**Comment by jtmkrueger** [comment] 2012-01-23 16:55
Did this get addressed in Rails 3.2?

**Comment by scottdavis** [comment] 2012-01-23 16:56
I think this got fixed in sass-rails with moving sass support directly into
sprockets but im not 100% sure.

On Mon, Jan 23, 2012 at 11:55 AM, jtmkrueger <
reply@reply.github.com

**Comment by scottdavis** [comment] 2012-01-23 16:59
even if it didn't using this gist: https://gist.github.com/9d27ab854dfadca917f1 in your gemfile will allow you to run compass watch ... warning its very edge and not yet stable.

**Comment by jtmkrueger** [comment] 2012-01-23 17:01
I made a couple arbitrary changes to some scss files to see if was faster after I upgraded.  It appeared to load quicker, but I can't say I ran any other tests beyond that.  I bumped my sass rails up to 3.2.3 when I upgraded to rails 3.2. My app is running sprockets 2.1.2.

**Comment by chriseppstein** [comment] 2012-01-31 16:24
In compass 0.12 you can run the compass watcher which should help. We'll continue working on the performance -- the issue is at the intersection of how sass and sprockets and compass interact so it's been tricky to nail down so far.

**Comment by noniq** [comment] 2012-02-05 17:50
I'm using Rails 3.2 and the Gems from https://gist.github.com/9d27ab854dfadca917f1 . Compiling my application.css.scss takes about **20ms** without compass – and goes up to about **2000ms** as soon as I add `@import "compass";`.

Compass itself uses many import directives for its own modules and mixins – this seems to be the main cause of the slowdown. 

I wrote a quick and dirty script to build a single giant `compass-all.scss` file by resolving all the imports statically: https://gist.github.com/1746744

Now when I use `@import "compass-all";` instead of `@import "compass";`, compilation time goes down again to about **220ms**. 

Maybe the compass gem should include a compass-all.scss file? Or a rake task to build a custom concatenated file (say, if I only want to use `compass/css3` for example)?

**Comment by scottdavis** [comment] 2012-02-06 00:21
not to mention the sprockets resolver is known to be slow when there are a lot of dependencies to resolve with hike slow

**Comment by chriseppstein** [comment] 2012-03-12 07:17
Please give the new compass-rails a try. We'll track any further performance issue at that repo now.

**Closed as completed by chriseppstein** 2012-03-12 07:17 UTC
Labels: rails31

**Comment by ckizer** [comment] 2013-01-31 16:10
It's awfully slow here too. Why does this get so little attention? Every single person doing ruby on rails has this problem. Ever startup. We wait for compiles, and have extremely frustrated designed who wait minutes EVER time they change a little block of css and want to check the work…

I don't understand why speed isn't given priority over everything. It's because it's hard to fix…

**Comment by knoopx** [comment] 2013-03-04 19:20
Here is my take on this:

```
sass (3.2.6)
sass-rails (3.2.6)
compass (0.12.2)
compass-rails (1.0.3)
sprockets (2.2.2)
hike (1.2.1)
```

A request just after modifying `application.css.sass` generates the following profiling report: http://d.pr/f/MWfo
wich as you can see there's something really weird going on with `Dir.open`

Tried to debug that and then got this: https://gist.github.com/knoopx/5082439

It looks like everything is working properly (except some dup lookups) but I personally think that sprockets/sass integration is broken by design. `@import` directive should not delegate the lookup to sprockets or sprockets should be smart enough to figure an optimum lookup path.

Here are some design flaws that I suspect that are the culpable of our current performance issues:
- For every `@import` directive we lookup both `file` and `_file` (Sass partial) through sprockets == 2x time
- For `@import example`, sprockets looks up both `example.sass` and `example/index.sass`
- On a Sass file modification, something somehow flushes Sprockets/Hike lookup cache, causing it to re-glob all the load paths (including the gem-vendored ones, which hypothetically should never change)
- Sprockets tries to locate Sass files on every gem-vendored javascript, stylesheet and image folders?¿?
- Hike is not smart enough to skip already looked up directories or `Hike::Index#entries` memoization is not 
  properly working. The above output was generated using this:
  
  ```
    @entries[key] ||= begin
      p "Hike::Index#entries(#{path})"
      Pathname.new(path).entries.reject { |entry| entry.to_s =~ /^\.|~$|^\#.*\#$/ }.sort
    end
  ```

**Comment by scottdavis** [comment] 2013-03-15 16:33
"I personally think that sprockets/sass integration is broken by design" we tried to work with the sprockets team to make our attachment easy. Our pull request got rejected back with 3.1 first dropped. I'm not sure if it was by design or just by ignorance. with rails 4 i may end up doing what middleman did and override the sass importer in sprockets. Which i hope will fix this issue since i will not need to reopen sprocket classes to get things hooked up correctly
