### ISSUE TITLE
Sprites from nested folders

### ISSUE THREAD

**Issue by aaronchi** [Compass/compass#370] opened 2011-05-03 16:37 UTC
Is it possible to change the sprites helper to work with nested folders? It makes it really inconvenient when I'm forced to leave all of my sprite folders at the top level of the images dir. This worked fine with lemonade.

**Comment by chriseppstein** [comment] 2011-05-04 04:03
Hmmm. I thought this worked. We'll look into it. What did you try doing and what did or didn't happen when you did that?

**Comment by scottdavis** [comment] 2011-05-04 13:28
i think you have to change your glob in the @import to be `@import "foo/**/*.png"`

**Comment by scottdavis** [comment] 2011-05-11 01:16
@aaronchi have you tried what i suggested above?

**Comment by scottdavis** [comment] 2011-05-11 02:42
scratch that this was a bug ive got a fix for it

**Comment by scottdavis** [comment] 2011-05-11 02:46
fixed by: 753ad37df743d7d39d1cec65df25aefec1ba5f87

**Closed as completed by scottdavis** 2011-05-11 02:46 UTC
Labels: sprites

**Comment by seantanly** [comment] 2011-09-22 08:13
Seems that this issue resurfaced in 0.12.alpha.0

Though compass is able to generate the sprite image, the image is placed in the top level of the image folder instead of in the nested folder.

Due to this, sprite map of similar name cannot be used.

e.g. 
images/theme/orange/icons/_.png
images/theme/black/icons/_.png

Seems that the sprite image of the first is being overwritten by the second.

**Comment by scottdavis** [comment] 2011-09-22 21:42
This problem has never come up before so for now im going to consider this an edge case and recommend that you don't nest and just use orange_icons, black_icons etc.

**Comment by scottdavis** [comment] 2011-09-22 21:43
also @seantan your issue isn't that same as this one this had to do with not finding the nested folders

**Comment by seantanly** [comment] 2011-09-28 05:53
ok, not nesting works.

Just thought that it would be cool if the generated sprites are created just 1 level below their source png folder.

Thanks for the suggestions.

**Comment by aaronchi** [comment] 2011-09-28 07:25
Yes... Would be nice if it worked with nesting :(

**Comment by scottdavis** [comment] 2011-09-28 17:23
Busy workin on extension registry but I'll take a patch if someone wants to submit one

**Comment by claicham** [comment] 2012-05-02 10:44
Sprites from nested folders with a name that contains only numbers produces this error:

error sass/xxx.scss (Line x of *.png: Invalid CSS after "$": expected identifier, was "24-sprite-base-...")

Changed the folder name from '24' to 'twentyfour' and it compiled correctly and produced the sprite.

**Comment by scottdavis** [comment] 2012-05-03 18:15
this is because the folder name becomes a sass variable by design so `$24` is not valid

**Comment by claicham** [comment] 2012-05-04 07:30
Thanks for the reply, that's fair enough, didn't mean it as a bug just for info if anyone else runs into the same issue. Folder structure for icons is normally by size on large projects I've worked on.

**Comment by eeroan** [comment] 2012-09-06 07:54
Is there currently any way for getting sprites from this kind of structure:

app/timetable/icons/.png
app/summary/icons/.png

And even better, having them merged in same sprite image?

**Comment by schneidafunk** [comment] 2013-07-31 20:05
I'm having the same problem with similar folder names, such as the example eeroan posted above.

**Comment by JawsomeJason** [comment] 2013-10-17 20:03
Still would like to be able to do this:

```
- ui
-- image
--- remove.png
-- remove.png
```

``` sass
@import 'ui/**/*.png';

@include ui-sprite( remove );
@include ui-sprite( image-remove );
```

Can we not generate our sprite variables/mixins by climbing up the directory chain?

**Comment by evanpurkhiser** [comment] 2014-03-17 08:34
Was there ever any sort of change for this? I agree with @thejase, it would be nice to have the sprite names namespaced by the folders they're in.
