### ISSUE TITLE
filter-gradient causing clipping on negative margin elements

### ISSUE THREAD

**Issue by lmartins** [Compass/compass#234] opened 2010-12-04 16:58 UTC
Certainly not an Compass Issue, but something i've just came up to.
If i apply negative-margin on a element inside a container which has filter-gradient applied, the elemento with negative-margin gets clipped and none of the know workarounds seems to solve the problem.

**Comment by chriseppstein** [comment] 2010-12-06 04:52
If you find the cause is anything compass related, do let us know. Closing for now.

**Closed as completed by chriseppstein** 2010-12-06 04:52 UTC
