### ISSUE TITLE
Needed: .sass-cache clearing

### ISSUE THREAD

**Issue by imathis** [Compass/compass#55] opened 2009-11-30 18:12 UTC
I've found that in several of my projects I've had trouble with compass seeing my configuration changes unless I manually clear my .sass-cache directory. Also when I'm running Compass watch, changes to the config file do not cause the sass to be recompiled. This seems like an oversight, because most of the configuration options would necessitate a rebuild. I often have to kill the watch process to run the update, and then re-run watch.

I think this seems like something that should be taken care of by Compass. I would assume that the desired behavior would be that an update to the configuration would cause the .sass-cache to be cleared upon the next recompile. I also feel that Compass watch should pay attention to the config file.

**Comment by johnthedebs** [comment] 2009-11-30 18:42
I was thinking about this just yesterday - I'll second this motion.

**Comment by chriseppstein** [comment] 2009-11-30 20:07
I will talk to nathan about whether this is a sass or compass bug.

**Comment by chriseppstein** [comment] 2009-12-01 18:35
If the configuration file changes, wipe out the sass cache and force
compilation. Closed by 3bb5e6d83d07044217e86b9e4216c7bbc6d6638d.

**Closed as completed by chriseppstein** 2009-12-01 18:35 UTC

**Comment by nex3** [comment] 2009-12-01 20:10
Just to be sure: this is not a Sass bug, correct?

**Comment by chriseppstein** [comment] 2009-12-01 21:06
Not a sass bug. When the configuration changes, there's no way for Sass to know that the function calls will generate different results. At first, I thought this bug and the one related to line_comments might be related via a root cause in sass, but no.
