### ISSUE TITLE
jRuby Support?

### ISSUE THREAD

**Issue by andrewoma** [Compass/compass#53] opened 2009-11-23 07:26 UTC
Hi, 

I've just tried getting the current version (0.8.17) to run under jRuby (1.4.0). 

It all seems ok up until I try to watch a project. It then fails within the monitoring code. (See the stack trace below).

Any chance of making this work under jRuby? Maybe a dumbed down file monitoring that just polls the SASS directory periodically?

FYI, the main reason I want to run under jRuby is so that I can write a Maven plugin, making compass more accessible to the Java world.

Cheers,
Andrew

> > > Compass is watching for changes. Press Ctrl-C to Stop.
> > > NoMethodError on line 170 of /private/tmp/gemsrepo/gems/gems/chriseppstein-compass-0.8.17/lib/vendor/fssm/tree.rb: undefined method `ftype' for nil:NilClass
> > >   /private/tmp/gemsrepo/gems/gems/chriseppstein-compass-0.8.17/lib/vendor/fssm/tree.rb:39:in`call'
> > >   /private/tmp/gemsrepo/gems/gems/chriseppstein-compass-0.8.17/lib/vendor/fssm/tree.rb:39:in `each'
> > >   /private/tmp/gemsrepo/gems/gems/chriseppstein-compass-0.8.17/lib/vendor/fssm/tree.rb:35:in`each'
> > >   /private/tmp/gemsrepo/gems/gems/chriseppstein-compass-0.8.17/lib/vendor/fssm/tree.rb:168:in `inject'
> > >   /private/tmp/gemsrepo/gems/gems/chriseppstein-compass-0.8.17/lib/vendor/fssm/tree.rb:168:in`ftype'
> > >   /private/tmp/gemsrepo/gems/gems/chriseppstein-compass-0.8.17/lib/vendor/fssm/tree.rb:153:in `files'
> > >   /private/tmp/gemsrepo/gems/gems/chriseppstein-compass-0.8.17/lib/vendor/fssm/state.rb:38:in`recache'
> > >   /private/tmp/gemsrepo/gems/gems/chriseppstein-compass-0.8.17/lib/vendor/fssm/state.rb:9:in `refresh'
> > >   /private/tmp/gemsrepo/gems/gems/chriseppstein-compass-0.8.17/lib/vendor/fssm/backends/polling.rb:10:in`add_path'
> > >   /private/tmp/gemsrepo/gems/gems/chriseppstein-compass-0.8.17/lib/vendor/fssm/monitor.rb:18:in `path'
> > >   /private/tmp/gemsrepo/gems/gems/chriseppstein-compass-0.8.17/lib/compass/commands/watch_project.rb:26:in`perform'
> > >   /private/tmp/gemsrepo/gems/gems/chriseppstein-compass-0.8.17/lib/compass/commands/watch_project.rb:25:in `each'
> > >   /private/tmp/gemsrepo/gems/gems/chriseppstein-compass-0.8.17/lib/compass/commands/watch_project.rb:25:in`perform'
> > >   /private/tmp/gemsrepo/gems/gems/chriseppstein-compass-0.8.17/lib/vendor/fssm.rb:19:in `call'
> > >   /private/tmp/gemsrepo/gems/gems/chriseppstein-compass-0.8.17/lib/vendor/fssm.rb:19:in`monitor'
> > >   /private/tmp/gemsrepo/gems/gems/chriseppstein-compass-0.8.17/lib/compass/commands/watch_project.rb:24:in `perform'
> > >   /private/tmp/gemsrepo/gems/gems/chriseppstein-compass-0.8.17/lib/compass/commands/base.rb:15:in`execute'
> > >   /private/tmp/gemsrepo/gems/gems/chriseppstein-compass-0.8.17/lib/compass/commands/project_base.rb:19:in `execute'
> > >   /private/tmp/gemsrepo/gems/gems/chriseppstein-compass-0.8.17/lib/compass/exec.rb:242:in`do_command'
> > >   /private/tmp/gemsrepo/gems/gems/chriseppstein-compass-0.8.17/lib/compass/exec.rb:57:in `perform!'
> > >   /private/tmp/gemsrepo/gems/gems/chriseppstein-compass-0.8.17/lib/compass/exec.rb:40:in`run!'
> > >   /private/tmp/gemsrepo/gems/gems/chriseppstein-compass-0.8.17/bin/compass:8
> > >   /private/tmp/gemsrepo/gems/gems/chriseppstein-compass-0.8.17/bin/compass:19:in `load'
> > >   /Users/andrew/dev/apps/jruby-1.4.0/bin/compass:19

**Comment by chriseppstein** [comment] 2009-11-23 16:50
Love the idea of a maven plugin. thanks for working on that.

fssm is designed to degrade gracefully to polling on unsupported platforms. But I don't see any reason why jruby should not be supported.

If you're in a big hurry, you can probably monkey patch fssm to force it into polling mode for your case while we work out a fix.

And, of course, any help you can offer in finding that fix would be appreciated.

**Comment by andrewoma** [comment] 2009-11-24 00:48
I'm working on a Mac, so I expect it's something related to JRuby not being able to hook into the FSEvents. 

As you suggested, I've just hacked it at present to always use polling. Maybe a flag (--forcepolling) would be enough to sort out JRuby support in the short term. Note: I still haven't actually verified that polling works under JRuby, but I assume it will.

With JRuby support sorted, the maven plugin should be fairly straight forward. (There's some messing around with having to automatically install the gems to the local fs, but it's all workable)

Cheers,
Andrew

**Comment by chriseppstein** [comment] 2009-11-24 00:52
FYI: I'm tracking the fix for the root cause here:

http://github.com/ttilley/fssm/issues/#issue/2

**Comment by chriseppstein** [comment] 2010-01-02 21:44
should be fixed in v0.10.0.pre3

**Closed as completed by chriseppstein** 2010-01-02 21:44 UTC
Labels: bug, blocker
