### ISSUE TITLE
-ms- prefix for gradients

### ISSUE THREAD

**Issue by pentzzsolt** [Compass/compass#1333] opened 2013-07-15 14:51 UTC
I noticed that when generating CSS3 gradients with the background-image mixin, there is no code generated with the -ms- prefix, even though the $experimental-support-for-microsoft variable is indeed set to true.

I looked into the code and noticed that it's just missing from the corresponding file. This unfortunately results in no IE10 support.

Am I missing something or is this really an issue?

**Comment by mirisuzanne** [comment] 2013-07-15 16:58
What version are you using?

If you check the [caniuse](http://caniuse.com/#feat=css-gradients) support tables, IE10 actually supports the new syntax. So the proper fix is not an -ms-prefix but the new official output. That fix has been made in the 0.13 alphas (master branch).

**Closed as completed by mirisuzanne** 2013-07-15 16:58 UTC

**Comment by pentzzsolt** [comment] 2013-07-15 19:03
I'm using Mixture, which is supposed to take care of everything for me. I have Ruby and Sass and Compass installed separately as well, latest versions.

Let me get this straight: so when using this mixin, it's supposed to generate the prefixed versions with the old syntax AND the unprefixed one with the new syntax as well?

**Comment by mirisuzanne** [comment] 2013-07-15 21:53
Yes - in the alpha release. Using Mixture, I'm sure you don't have alpha yet.

**Comment by pentzzsolt** [comment] 2013-07-16 21:15
Yes, you were right. Thank you Eric, you helped me a lot!

**Comment by markdavies** [comment] 2014-01-10 20:59
Not sure if this is still an issue, but I think the problem is that IE10 requires the newer spec for gradient directions (e.g. "to bottom" instead of "top"). This link nicely explains the problem:
http://joshuapaling.com/post/compass-background-gradients-not-working-ie10
