### ISSUE TITLE
compass watch gives ... interesting results

### ISSUE THREAD

**Issue by holizz** [Compass/compass#190] opened 2010-09-03 09:49 UTC
compass watch [directory]
... compiles correctly
... edit partials/_layout.sass
... The CSS output contains a literal @import, and get this output:

> > > Change detected to: [...]/src/screen.sass
> > > overwrite screen.css
> > > WARNING: Neither partials/layout.sass nor .scss found. Using partials/layout.css instead.
> > > This behavior is deprecated and will be removed in a future version.
> > > If you really need partials/layout.css, import it explicitly.

When you first run it (like with compass compile) it works correctly. After things are edited it starts getting confused.

Compass 0.10.5 (from rubygems, not github)

**Comment by chriseppstein** [comment] 2010-10-30 23:48
Are you still having this problem? If so, I cannot reproduce it. I need info on what is unique about your system.

**Comment by holizz** [comment] 2010-11-09 13:11
Yes. But without the warning.

Now if you edit _layout.sass, screen.css will contain "@import url(layout.css)" (where it should be merging _layout.sass into the same file).

This also occurs when you use "while true; do compass compile; done", which means I have to put an rm -rf in there, which makes it _very_ annoying to use.

What might be unique about my system?
I'm using Arch on both machines I've noticed the bug on. One is 64-bit running MRI 1.9.2p0, compass 0.10.5. The other is 32-bit with MRI 1.8.7, compass 0.10.6. I can't think of anything else.

**Comment by henry74** [comment] 2010-12-31 01:32
Getting the following similar error when using compass watch:

~/Documents/Ruby/awesome$ bundle exec compass watch
WARNING: Neither base.sass nor .scss found. Using base.css instead.
This behavior is deprecated and will be removed in a future version.
If you really need base.css, import it explicitly.

Here is my compass.rb file which is located a config folder one down from the app root directory:
require 'compass'

# Require any additional compass plugins here.

# Set this to the root of your project when deployed:

http_path = "/"
css_dir = "public/css"
http_stylesheets_path = "/stylesheets"
sass_dir = "views/stylesheets"
images_dir = "public/images"
http_images_path = "/images"
javascripts_dir = "public/javascripts"
output_style = :expanded
environment = :development

# To enable relative paths to assets via compass helper functions. Uncomment:

relative_assets = true

I'm not clear why it cannot find the _base.scss file which is located in the folder views/stylesheets/partials

**Comment by kajetanowicz** [comment] 2011-04-24 15:33
I had exact the same problem. I was getting @import('blueprint.css') literals in my screen.css ( without using compass watch) . For some reason when I removed sass.rb from initializers directory everything started working correctly.

**Comment by chriseppstein** [comment] 2011-04-24 17:09
@kajetanowicz What did your sass.rb do? If it overwrote the template locations instead of adding to it, then I would expect this behavior.

**Comment by kajetanowicz** [comment] 2011-04-24 17:39
Yep, that's exactly what happened. In initializers/sass.rb  I had Sass::Plugin.options[:css_location]  = "public/stylesheets" , in compass.rb: css_dir = "public/stylesheets/compiled".  I've been using Sass in my project for a while but couple days ago i decided to give Compass a try. Because this behaviour might not be so obvious for newcomers like me, it would be great to find short note about it somewere.  Thanks.

**Comment by chriseppstein** [comment] 2011-04-25 15:03
I just don't see this issue. Can you guys retest with the latest sass 3.1 and compass v0.11 and tell me if you're having issues?

**Comment by chriseppstein** [comment] 2011-05-01 16:57
closing

**Closed as completed by chriseppstein** 2011-05-01 16:57 UTC
Labels: unverified bug
