### ISSUE TITLE
Sprite relative path set from image path instead of project path.

### ISSUE THREAD

**Issue by GabrielCaronLecuyer** [Compass/compass#1268] opened 2013-04-23 21:33 UTC
When compiling a sprite, the sprite-map returns a url relative to the image path, and not from the project path.  Having the url returned from the project path would be usefull when creating custom mixins to work with the sprites.

example: with the images path : projectpath/images

background: sprite-map("/icons/*.png"); no-repeat;
returns  : background: url(/icons-sfad45165e8.png) no-repeat;
instead of : background: url(../images/icons-sfad45165e8.png) no-repeat;

**Comment by scottdavis** [comment] 2013-05-01 13:16
Sprites should be saved relative to the generated_images_path is that set correctly?

**Comment by GabrielCaronLecuyer** [comment] 2013-05-01 13:58
Hi Scott,

I did not setup the "generated_images_path" in the config.rb file, but i did setup the "image_dir" and the "generated_images_dir" properties.

The project directory structure I have is the following (quite standard I think)

-MyProject (folder)
    -images (folder)
        -icons (folder)
            -all icons files (.png)

The sprite is saved in the right path (in the images folder, no problem there).

The problem is that the path returned by the sprite-map function does not returned the correct path (it returns "/icons-sfad45165e8.png" instead of "../images/icons-sfad45165e8.png") in my css.  Standard browser does not recognise the path returned by the sprite-map function since it's not relative to the project path, but to the generated images path.

I am using scout to generate my css.  I believe the problem is coming from the compass used by scout, but I migth be wrong. thks.

**Comment by chriseppstein** [comment] 2013-05-22 00:41
Was just bit by this at work >_<

**Comment by chriseppstein** [comment] 2013-05-22 00:43
Dupe of #834.

**Closed as completed by chriseppstein** 2013-05-22 00:43 UTC
Labels: blocker
