### ISSUE TITLE
undefined method `static_root' for #<Sprockets::Index>

### ISSUE THREAD

**Issue by rwz** [Compass/compass#527] opened 2011-09-01 03:49 UTC
I've made a blank new rails 3.1 app with compass and one sass file with sprites. And the `assets:precompile` rake task fails on this setup with two different error messages.

You can see the test app here: https://github.com/rwz/compass_static_root_bug

**Comment by guilleiguaran** [comment] 2011-09-01 04:12
The error of the second run was fixed with #2768, I don't have idea about the first one

**Comment by guilleiguaran** [comment] 2011-09-01 04:14
The first one:

https://github.com/chriseppstein/compass/commit/7147147e24121ffb03044c638a6a8b02b8fccb7f#L0R68

static_root was deprecated in Sprockets

**Comment by kremso** [comment] 2011-09-06 21:18
@guilleiguaran: I was able to fix the first error by using the code you suggested.

https://github.com/kremso/compass/commit/1e5debe9388505d9dc993d4599d8dca696833f37

However, that didn't fix the second error. I was able to workaround that one by setting this in production.rb

   config.assets.compile = true

**Comment by guilleiguaran** [comment] 2011-09-06 21:23
@kremso, try using rails from 3-1-stable branch

**Comment by chriseppstein** [comment] 2011-09-13 06:24
confirmed. this is a version inconsistency between rails and sprockets. nothing to do w/ compass.

**Comment by rwz** [comment] 2011-09-13 06:44
What about the static root bug? It's still not fixed in current master.

**Comment by chriseppstein** [comment] 2011-09-13 06:51
my bad. Compass does refer to static root.

**Comment by adamhooper** [comment] 2011-09-14 15:09
I've switched to kremso's commit 1e5debe9388505d9dc993d4599d8dca696833f37 instead of 0.12.alpha.0. It works for me. Any reason not to merge it?

**Comment by guilleiguaran** [comment] 2011-09-14 15:11
@adamh looks like @kremso haven't send a pull request

**Comment by rwz** [comment] 2011-09-15 12:17
Switched on rails 3.1.1.rc1 with kremso's compass fork. Works fine so far.

**Comment by kremso** [comment] 2011-09-17 09:57
Pull request sent.

**Comment by matsimitsu** [comment] 2011-10-07 09:20
Any updates on this one? Still getting the issue :)

**Comment by scottdavis** [comment] 2011-10-08 00:39
this should be in master https://github.com/chriseppstein/compass/commit/fe4edff7d4980b50ae377336cf8ccfbc284bfaaa

**Closed as completed by scottdavis** 2011-10-08 00:39 UTC

**Comment by agibralter** [comment] 2011-10-10 14:43
Any chance for a 0.12.alpha.1?
