### ISSUE TITLE
Rails.root is nil! with compass 1.0.0.alpha.15 & sass 3.3.0.rc.2 in clean new rails 3.2.14

### ISSUE THREAD

**Issue by ahmeij** [Compass/compass#1475] opened 2013-12-10 09:09 UTC
Hi, I have searched for a day to find the exact cause and or solution of this problem but I have not gotten much further.

I'm guessing the compass requires sass too early in the rails boot process. 

I understand this is an alpha version and I'd like to help solve this, however I need a pointer as where to start looking :)

I had this problem in a complex rails app but it can be reproduced simply by:

Rails 3.2.14

`rails new CompassTest`
`cd CompassTest`
`vi Gemfile`  (change asset group to below)

```
group :assets do
  gem 'coffee-rails', '~> 3.2.1'
  gem "sass", "~> 3.3.0.rc.2"
  gem "compass", "~> 1.0.0.alpha.15"
  gem "sass-rails"
  gem "compass-rails" 
end
```

`rails s` will lead to:

```
/opt/rubies/ruby-1.9.3-p392/lib/ruby/gems/1.9.1/gems/sass-3.3.0.rc.2/lib/sass/util.rb:450:in `rails_root': ERROR: Rails.root is nil! (RuntimeError)
from /opt/rubies/ruby-1.9.3-p392/lib/ruby/gems/1.9.1/gems/sass-3.3.0.rc.2/lib/sass/plugin/rails.rb:11:in `default_options'
from /opt/rubies/ruby-1.9.3-p392/lib/ruby/gems/1.9.1/gems/sass-3.3.0.rc.2/lib/sass/plugin/configuration.rb:33:in `options'
from /opt/rubies/ruby-1.9.3-p392/lib/ruby/gems/1.9.1/gems/sass-3.3.0.rc.2/lib/sass/plugin/compiler.rb:38:in `initialize'
from /opt/rubies/ruby-1.9.3-p392/lib/ruby/gems/1.9.1/gems/sass-3.3.0.rc.2/lib/sass/plugin.rb:63:in `new'
from /opt/rubies/ruby-1.9.3-p392/lib/ruby/gems/1.9.1/gems/sass-3.3.0.rc.2/lib/sass/plugin.rb:63:in `compiler'
from /opt/rubies/ruby-1.9.3-p392/lib/ruby/gems/1.9.1/gems/sass-3.3.0.rc.2/lib/sass/plugin.rb:121:in `options'
from /opt/rubies/ruby-1.9.3-p392/lib/ruby/gems/1.9.1/gems/sass-3.3.0.rc.2/lib/sass/plugin/rails.rb:24:in `<top (required)>'
from /opt/rubies/ruby-1.9.3-p392/lib/ruby/gems/1.9.1/gems/sass-3.3.0.rc.2/lib/sass/plugin.rb:128:in `require'
from /opt/rubies/ruby-1.9.3-p392/lib/ruby/gems/1.9.1/gems/sass-3.3.0.rc.2/lib/sass/plugin.rb:128:in `<top (required)>'
from /opt/rubies/ruby-1.9.3-p392/lib/ruby/gems/1.9.1/gems/compass-core-1.0.0.alpha.15/lib/compass/core.rb:51:in `require'
from /opt/rubies/ruby-1.9.3-p392/lib/ruby/gems/1.9.1/gems/compass-core-1.0.0.alpha.15/lib/compass/core.rb:51:in `<top (required)>'
from /opt/rubies/ruby-1.9.3-p392/lib/ruby/gems/1.9.1/gems/compass-1.0.0.alpha.15/lib/compass.rb:15:in `require'
from /opt/rubies/ruby-1.9.3-p392/lib/ruby/gems/1.9.1/gems/compass-1.0.0.alpha.15/lib/compass.rb:15:in `block in <top (required)>'
from /opt/rubies/ruby-1.9.3-p392/lib/ruby/gems/1.9.1/gems/compass-1.0.0.alpha.15/lib/compass.rb:5:in `each'
from /opt/rubies/ruby-1.9.3-p392/lib/ruby/gems/1.9.1/gems/compass-1.0.0.alpha.15/lib/compass.rb:5:in `<top (required)>'
from /opt/rubies/ruby-1.9.3-p392/lib/ruby/gems/1.9.1/gems/bundler-1.3.5/lib/bundler/runtime.rb:72:in `require'
from /opt/rubies/ruby-1.9.3-p392/lib/ruby/gems/1.9.1/gems/bundler-1.3.5/lib/bundler/runtime.rb:72:in `block (2 levels) in require'
from /opt/rubies/ruby-1.9.3-p392/lib/ruby/gems/1.9.1/gems/bundler-1.3.5/lib/bundler/runtime.rb:70:in `each'
from /opt/rubies/ruby-1.9.3-p392/lib/ruby/gems/1.9.1/gems/bundler-1.3.5/lib/bundler/runtime.rb:70:in `block in require'
from /opt/rubies/ruby-1.9.3-p392/lib/ruby/gems/1.9.1/gems/bundler-1.3.5/lib/bundler/runtime.rb:59:in `each'
from /opt/rubies/ruby-1.9.3-p392/lib/ruby/gems/1.9.1/gems/bundler-1.3.5/lib/bundler/runtime.rb:59:in `require'
from /opt/rubies/ruby-1.9.3-p392/lib/ruby/gems/1.9.1/gems/bundler-1.3.5/lib/bundler.rb:132:in `require'
from /data/CompTest/config/application.rb:7:in `<top (required)>'
from /opt/rubies/ruby-1.9.3-p392/lib/ruby/gems/1.9.1/gems/railties-3.2.14/lib/rails/commands.rb:53:in `require'
from /opt/rubies/ruby-1.9.3-p392/lib/ruby/gems/1.9.1/gems/railties-3.2.14/lib/rails/commands.rb:53:in `block in <top (required)>'
from /opt/rubies/ruby-1.9.3-p392/lib/ruby/gems/1.9.1/gems/railties-3.2.14/lib/rails/commands.rb:50:in `tap'
from /opt/rubies/ruby-1.9.3-p392/lib/ruby/gems/1.9.1/gems/railties-3.2.14/lib/rails/commands.rb:50:in `<top (required)>'
from script/rails:6:in `require'
from script/rails:6:in `<main>'
```

**Comment by hagenburger** [comment] 2013-12-10 10:31
This is a duplicate of https://github.com/chriseppstein/compass/issues/1462 which has been moved into Sass’ issues:

https://github.com/nex3/sass/issues/1033

I’m having the same issues in a project.

Btw. you should update to Rails 3.2.16 asap.

**Closed as completed by hagenburger** 2013-12-10 10:31 UTC
