### ISSUE TITLE
Support for Sass Source Maps

### ISSUE THREAD

**Issue by Snugug** [Compass/compass#1189] opened 2013-02-27 21:15 UTC
While I'm aware I'm much too far ahead of the curve on this, I've noticed an interesting inconsistency. Using Compass 0.13.alpha.2 and Sass 3.3.0.alpha.101, if I compile using Sass and the `--sourcemap` option, Sass will spit out the source maps as expected; however, if I add `sass_options = {:sourcemap => true}` to Compass's config.rb file, no sourcemap is produced. I'd like to be able to use Compass to generate Sass sorucemaps.

**Comment by 37mm** [comment] 2013-03-11 21:10
+1, would love to see this also!

**Comment by chriseppstein** [comment] 2013-03-16 20:35
Duplicate of #1108

**Closed as completed by chriseppstein** 2013-03-16 20:35 UTC
