### ISSUE TITLE
url functions no longer respect paths after a recompile

### ISSUE THREAD

**Issue by krisbulman** [Compass/compass#989] opened 2012-08-13 03:11 UTC
OS X 10.7.3
Ruby 1.9.3p125
Sass 3.2.0 (Media Mark)
Compass 0.13.alpha.0 (Markab)

Using relative_assets, image-url() and font-url() only pass the right path after a clean compile, and any subsequent manual compile produces only a filename with no path. This bug has been around since 3.2 alpha 275 of Sass [this commit](https://github.com/nex3/sass/commit/e36aedc9b57e09fc29bee431d89e535806af8779). 

example:

```
background: url("../../images/grid-col-numbers.png?1343702520") no-repeat scroll 0 0px;
```

modifying any file in the project, then just running _compass compile_ changes the path to a wrong one: 

```
background: url("grid-col-numbers.png?1343702520") no-repeat scroll 0 0px;
```

config.rb

```
images_dir      = "images"
relative_assets = true;
```

**EDIT:** updated with sample project details:

I've created a sample project that shows the problem: 

```
git clone git://github.com/krisbulman/compass-image-url-example.git
```

http://github.com/krisbulman/compass-image-url-example

Steps to reproduce: 
1. compass compile (css dir and stylesheet gets created, image path ok in style.css)
2. edit _mixins.scss but make no code changes
3. compass compile (check  style.css, image path borked)

**EDIT:** updated with debugging details and commit

debugging: https://gist.github.com/4d16fdbe950ecbe582de
slight progress: https://github.com/chriseppstein/compass/pull/1062

**Comment by chriseppstein** [comment] 2012-08-13 05:05
Seems likely that you've got compilation happening twice and it's misconfigured in one of them. 

Hunt & pecked on my iPhone... Sorry if it's brief!

**Comment by krisbulman** [comment] 2012-08-13 12:57
I did forget to mention I am using image-url in a loop, and passing the results as a list. 

I've created a sample project that shows the problem: 

```
git clone git://github.com/krisbulman/compass-image-url-example.git
```

http://github.com/krisbulman/compass-image-url-example

Steps to reproduce: 
1. compass compile (css dir and stylesheet gets created, image path ok in style.css)
2. edit _mixins.scss but make no code changes
3. compass compile (check  style.css, image path borked)

**Comment by krisbulman** [comment] 2012-08-14 16:51
Can anyone else reproduce this?

**Comment by chriseppstein** [comment] 2012-08-14 17:12
I can reproduce it. Very strange :(

**Comment by MoOx** [comment] 2012-08-14 17:44
I don't know if it's the same problem, but I've got a weird issue similar (yesterday and today) with `font-url()`, which, with the same "instance" of `compass watch` first use the correct fonts_dir, then, later, use a absolute path. Really weird. I've to stop compass watch, then relaunch it and save a file to have to correct font-url() back.

**Comment by krisbulman** [comment] 2012-08-14 17:51
I can confirm the same happens with `font-url()`, I have updated the sample project to show the problem, follow the same steps to reproduce. I haven't included a font because it's unnecessary.

**Comment by krisbulman** [comment] 2012-08-16 14:50
This problem persists when rolling back compass versions (tried back to 12.1), so I started rolling back sass releases to determine when the bug was introduced. 

The bug was introduced in  3.2.0.alpha.277 released on July 27, 2012. 
Rolling back to  3.2.0.alpha.275 released on July 16, 2012 fixes the problem. 

For others who need this to work, use alpha 275 for now: 

```
sudo gem install sass -v 3.2.0.alpha.275
```

UPDATE: 

commit that this stops working on stable is: https://github.com/nex3/sass/commit/daf44b6e5e3a25e1fadb77a4161ffe27edea74ab (merge conflict)
last commit I can get to work for Sass on the stable branch is https://github.com/nex3/sass/commit/2798d48d024b5b1452b5d0e1381d7e4fe4caad77

Should this be a Sass bug report?

**Comment by chriseppstein** [comment] 2012-08-16 18:05
Good sleuthing, this will help me debug the issue. I'm not sure who's bug this is, so let's just leave it here for now until I diagnose it.

**Comment by idflood** [comment] 2012-08-22 12:09
I stumbled on this bug when I wanted to try zurb foundation today. Uninstalling sass 3.2.x told me
`zurb-foundation-3.0.9 depends on [sass (>= 3.2.0)]`

**Comment by krisbulman** [comment] 2012-08-22 14:16
@idflood If you're looking to roll back to the working alpha version that doesn't produce this problem, first install the alpha 275 version:

```
sudo gem install sass -v 3.2.0.alpha.275
```

then uninstall 3.2 and it won't give you that warning:

```
sudo gem uninstall sass
```

(choose the sass version that is not 275alpha)

Note: I have just confirmed this bug also persists in 3.2.1

**Comment by teppeis** [comment] 2012-09-04 04:13
I have this same problem in sass-3.2.1 and compass-0.12.2.

**Comment by smt** [comment] 2012-09-06 19:14
Confirmed with sass-3.2.1 and compass-0.12.2

**Comment by chrisvanpatten** [comment] 2012-09-08 23:35
Another confirmation with sass-3.2.1 and compass-0.12.2. I'm also using guard-compass ([my own patch](https://github.com/chrisvanpatten/guard-compass/tree/patch-1)), although I'm getting the problem when not using it as well.

**Comment by krisbulman** [comment] 2012-09-20 02:07
OK, I did much more sleuthing on this problem. The commit that I mentioned stopped working earlier was a merge of two branches. I followed the other branch back and determined that this is the commit that creates the problem. 

https://github.com/nex3/sass/commit/e36aedc9b57e09fc29bee431d89e535806af8779

The parent commit works: https://github.com/nex3/sass/commit/0db3cb6c69625af872dc39f2694ba1017516c2bb

**Comment by krisbulman** [comment] 2012-10-26 18:26
I did a bit of debugging around this, and documented it here: 

https://gist.github.com/4d16fdbe950ecbe582de

If anyone who is familiar with ruby/ruby debugging can point me on a fruitful path, I'd be grateful.

**Comment by krisbulman** [comment] 2012-10-27 01:19
That commit actually seems to solve the problem, and all debugging in the previous comment now report properly on second compile. What I'm not completely sure of is why it actually solves the problem, but I hope it's on the right path!  I got the idea from the :filename string replacement in the new sass tests from the commit that caused this problem in the first place.

**Comment by scottdavis** [comment] 2012-11-01 19:46
Ive tracked it down to this method so far: https://github.com/chriseppstein/compass/blob/stable/lib/compass/sass_extensions/functions/urls.rb#L223-227

**Comment by scottdavis** [comment] 2012-11-01 19:48
Problem is https://github.com/chriseppstein/compass/blob/stable/lib/compass/sass_extensions/functions/urls.rb#L224 is returning nil on an imported file

**Comment by scottdavis** [comment] 2012-11-01 19:54
Which is set here: https://github.com/chriseppstein/compass/blob/master/lib/compass/compiler.rb#L161

But dumping out the value always shows it set in both cases? where is it getting removed? Possibly something is not getting duped?

**Comment by scottdavis** [comment] 2012-11-01 20:01
When you dump the sass options on a _mixin.scss change there is not css_filename set

<pre>
{:style=>:expanded, :load_paths=>[/Volumes/SSD/Work/compass-image-url-example/sass, /Volumes/SSD/Work/compass/frameworks/blueprint/stylesheets, /Volumes/SSD/Work/compass/frameworks/compass/stylesheets, /Users/sdavis/.compass/extensions/testing/stylesheets, Compass::SpriteImporter], 
:cache=>true, :cache_location=>"/Volumes/SSD/Work/compass-image-url-example/.sass-cache", :syntax=>:scss, :filesystem_importer=>Sass::Importers::Filesystem, :cache_store=>#<Sass::CacheStores::Chain:0x007ff33c5f0e38 @caches=[#<Sass::CacheStores::Memory:0x007ff33c5f1e28 @contents={"c1ef5c9f97d8281df6465a6e757ee57af51e322c/style.scssc"=>{:sha=>"08f2e2e5b03e6335e8f70d38f7778867c5aec147", :obj=>(Sass::Tree::RootNode Sass::Tree::ImportNode (Sass::Tree::RuleNode Sass::Tree::PropNode Sass::Tree::PropNode Sass::Tree::PropNode Sass::Tree::PropNode Sass::Tree::MixinNode) Sass::Tree::MixinNode)}, "c1ef5c9f97d8281df6465a6e757ee57af51e322c/_mixins.scssc"=>{:sha=>"433d307191c4c22cd423d45da437c99fc3df6ce0", :obj=>(Sass::Tree::RootNode Sass::Tree::VariableNode Sass::Tree::VariableNode Sass::Tree::VariableNode Sass::Tree::CommentNode (Sass::Tree::FunctionNode Sass::Tree::ReturnNode) (Sass::Tree::RuleNode Sass::Tree::PropNode) Sass::Tree::CommentNode (Sass::Tree::MixinDefNode Sass::Tree::VariableNode Sass::Tree::VariableNode Sass::Tree::VariableNode Sass::Tree::PropNode Sass::Tree::PropNode Sass::Tree::PropNode Sass::Tree::PropNode Sass::Tree::CommentNode Sass::Tree::VariableNode (Sass::Tree::ForNode Sass::Tree::VariableNode Sass::Tree::VariableNode Sass::Tree::VariableNode) Sass::Tree::PropNode) Sass::Tree::CommentNode (Sass::Tree::MixinDefNode (Sass::Tree::DirectiveNode Sass::Tree::PropNode Sass::Tree::PropNode Sass::Tree::PropNode Sass::Tree::PropNode Sass::Tree::PropNode)))}}>, #<Sass::CacheStores::Filesystem:0x007ff33c5f0e60 @cache_location="/Volumes/SSD/Work/compass-image-url-example/.sass-cache">]>, 
:line_comments=>true, :importer=>/Volumes/SSD/Work/compass-image-url-example/sass, :compass=>{:logger=>#<Compass::Logger:0x007ff33c5f73f0 @options={}, @actions=[:directory, :exists, :remove, :create, :overwrite, :compile, :error, :identical, :warning]>, :environment=>:development}, :filename=>"/Volumes/SSD/Work/compass-image-url-example/sass/_mixins.scss", :original_filename=>"/Volumes/SSD/Work/compass-image-url-example/sass/style.scss", :property_syntax=>nil}
</pre>

**Comment by scottdavis** [comment] 2012-11-01 20:03
But it is when you change the top level file.

<pre>
{:style=>:expanded, :load_paths=>[/Volumes/SSD/Work/compass-image-url-example/sass, /Volumes/SSD/Work/compass/frameworks/blueprint/stylesheets, /Volumes/SSD/Work/compass/frameworks/compass/stylesheets, /Users/sdavis/.compass/extensions/testing/stylesheets, Compass::SpriteImporter], :cache=>true, :cache_location=>"/Volumes/SSD/Work/compass-image-url-example/.sass-cache", :syntax=>:scss, :filesystem_importer=>Sass::Importers::Filesystem, :cache_store=>#<Sass::CacheStores::Chain:0x007f876c5ece28 @caches=[#<Sass::CacheStores::Memory:0x007f876c5ede18 @contents={"c1ef5c9f97d8281df6465a6e757ee57af51e322c/style.scssc"=>{:sha=>"f5597d0e6e0f7f82c7e4c52780d70130c3d28ea4", :obj=>(Sass::Tree::RootNode Sass::Tree::ImportNode (Sass::Tree::RuleNode Sass::Tree::PropNode Sass::Tree::PropNode Sass::Tree::PropNode Sass::Tree::PropNode Sass::Tree::MixinNode) (Sass::Tree::RuleNode Sass::Tree::PropNode) Sass::Tree::MixinNode)}, "c1ef5c9f97d8281df6465a6e757ee57af51e322c/_mixins.scssc"=>{:sha=>"433d307191c4c22cd423d45da437c99fc3df6ce0", :obj=>(Sass::Tree::RootNode Sass::Tree::VariableNode Sass::Tree::VariableNode Sass::Tree::VariableNode Sass::Tree::CommentNode (Sass::Tree::FunctionNode Sass::Tree::ReturnNode) (Sass::Tree::RuleNode Sass::Tree::PropNode) Sass::Tree::CommentNode (Sass::Tree::MixinDefNode Sass::Tree::VariableNode Sass::Tree::VariableNode Sass::Tree::VariableNode Sass::Tree::PropNode Sass::Tree::PropNode Sass::Tree::PropNode Sass::Tree::PropNode Sass::Tree::CommentNode Sass::Tree::VariableNode (Sass::Tree::ForNode Sass::Tree::VariableNode Sass::Tree::VariableNode Sass::Tree::VariableNode) Sass::Tree::PropNode) Sass::Tree::CommentNode (Sass::Tree::MixinDefNode (Sass::Tree::DirectiveNode Sass::Tree::PropNode Sass::Tree::PropNode Sass::Tree::PropNode Sass::Tree::PropNode Sass::Tree::PropNode)))}}>, #<Sass::CacheStores::Filesystem:0x007f876c5ece50 @cache_location="/Volumes/SSD/Work/compass-image-url-example/.sass-cache">]>, :line_comments=>true, :importer=>/Volumes/SSD/Work/compass-image-url-example/sass, :compass=>{:logger=>#<Compass::Logger:0x007f876c5f33b8 @options={}, @actions=[:directory, :exists, :remove, :create, :overwrite, :compile, :error, :identical, :warning]>, :environment=>:development}, :filename=>"/Volumes/SSD/Work/compass-image-url-example/sass/_mixins.scss", :css_filename=>"/Volumes/SSD/Work/compass-image-url-example/css/style.css", :original_filename=>"/Volumes/SSD/Work/compass-image-url-example/sass/style.scss", :property_syntax=>nil}
</pre>

**Comment by scottdavis** [comment] 2012-11-01 20:48
Could it be because the options became read only? 
https://github.com/nex3/sass/commit/e36aedc9b57e09fc29bee431d89e535806af8779#L1L21

**Comment by chriseppstein** [comment] 2012-11-01 22:46
Fixed in Sass.

**Closed as completed by chriseppstein** 2012-11-01 22:46 UTC
Labels: bug, blocker, needs patch

**Comment by krisbulman** [comment] 2012-11-02 00:07
Amazing! see @nex3's fix here https://github.com/nex3/sass/issues/412
