### ISSUE TITLE
Compass `watch` broken on OS X 10.8 Mountain Lion Developer Preview (Ruby 1.8.7)

### ISSUE THREAD

**Issue by OliverJAsh** [Compass/compass#732] opened 2012-02-24 15:52 UTC
When running `$ compass watch` on OS X 10.8 Mountain Lion (Developer Preview), this bug appears:

```
/Library/Ruby/Gems/1.8/gems/fssm-0.2.7/lib/fssm/backends/fsevents.rb:27: [BUG] Segmentation fault
ruby 1.8.7 (2011-12-28 patchlevel 357) [universal-darwin12.0]

Abort trap: 6 
```

**Comment by chriseppstein** [comment] 2012-03-12 07:04
We'll probably need to switch from fssm to [listen](https://github.com/guard/listen) in order to address this. Or maybe just upgrade fsevents. Since you're on the cutting edge, some more investigation would be greatly appreciated.

**Comment by ryanjcollier** [comment] 2012-03-13 01:13
I updated both fsevents and the compass gem, but still get the same issue. It still works for the initial compile, but will crash on any subsequent changes to the sass. For now the only work around is to run "compass watch" each time you want to view the compiled changes. This would be a nice fix as defeats the productivity enhancements achieved by using watch ... and is quite annoying. =D

**Comment by scottdavis** [comment] 2012-03-15 17:28
can you try the latest guard from master and see if it works? if it doesn't put a ticket in for the listen gem https://github.com/guard/listen this is much higher level then compass its self.

**Comment by scottdavis** [comment] 2012-03-15 17:39
i was going handel this from the listen side since im working on that project

**Comment by scottdavis** [comment] 2012-03-15 17:40
freaking ninja reopening!

**Comment by scottdavis** [comment] 2012-03-15 17:41
https://github.com/guard/listen/issues/14

**Comment by chriseppstein** [comment] 2012-03-15 18:04
Don't want to close the issue on our end until it's fixed in compass

**Comment by scottdavis** [comment] 2012-03-15 18:07
i added a new label to test after listen integration and tagged a few tickets

**Comment by ttilley** [comment] 2012-03-16 06:27
Nuke the ruby cocoa fsevent backend. It's been broken since lion, and just if'd out. I'll update FSSM to just destroy it, though listen is the way moving forward.

**Comment by chriseppstein** [comment] 2012-03-16 06:32
Workaround on mountain lion: `compass watch --poll`

**Comment by travyo** [comment] 2012-03-22 23:16
Was having same problem.  Confirmed that above workaround works for a directory watch as well.

**Comment by gpbmike** [comment] 2012-07-25 21:53
Still an issue, workaround still works. :D

**Comment by chriseppstein** [comment] 2012-07-25 23:27
Noted.

**Comment by jnettik** [comment] 2012-08-01 17:27
I'm having this problem as well. Confirm workaround works.

**Comment by jnettik** [comment] 2012-08-02 05:22
So I updated the fssm gem to version 0.2.9 and compass watch seems to work again (although there is the fun message about fssm being dead that pops up now). I installed listen and nothing seems to have changed. Do I need to do something more in order to get Compass (v0.12.1/ sass v3.1.15) working with listen?

**Comment by MoOx** [comment] 2012-08-04 06:43
I've personally no problem with mountain lion now.

**Comment by cri5ti** [comment] 2012-08-14 12:38
For me, updating the fssm (to 0.2.9) fixed the issue. I get that warning like @jnettik mentioned, but works for me. (I also reinstalled latest version of compass)

`gem update fssm`

**Comment by osserpse** [comment] 2012-08-17 21:08
Confirms that workaround on mountain lion works: `compass watch --poll`
But after `gem update fssm` there is no need for the workaround longer

**Comment by scottdavis** [comment] 2012-10-20 21:48
try listen branch

**Closed as completed** 2014-08-01 21:53 UTC
Labels: Test after listen integration
