### ISSUE TITLE
compass watch isn't watching files

### ISSUE THREAD

**Issue by chrisdrackett** [Compass/compass#394] opened 2011-05-19 21:08 UTC
No idea why this stopped working. I'm on a mac with 0.11.1:

> > compass version
> >   Compass 0.11.1 (Antares)
> >   Copyright (c) 2008-2011 Chris Eppstein
> >   Released under the MIT License.
> >   Compass is charityware.
> >   Please make a tax deductable donation for a worthy cause: http://umdf.org/compass

when I first run watch it'll find all changes, but any changes I make after that are not picked up. I've tried on multiple projects and it seems to be every compass project on my computer.

**Comment by scottdavis** [comment] 2011-05-19 21:32
which version of fssm do you have installed? are you using a Gemfile in your project?

**Comment by chrisdrackett** [comment] 2011-05-19 22:03
I'm just using compass on its own for these projects, fssm is 0.2.7

**Comment by chriseppstein** [comment] 2011-05-19 23:09
Please upgrade sass, haml and fssm to the latest versions and let me know if it fixes it. 

Hunt & pecked on my iPhone... Sorry if it's brief!

**Comment by chrisdrackett** [comment] 2011-05-23 18:44
no worries! everything is at the latest version, but no change. I'm now using this method (which I actually like better:)

http://www.senchatouchbits.com/4/better-alternatives-to-compass-watch.html

**Comment by wrumsby** [comment] 2011-05-24 09:39
We've experienced something similar - of the 4-5 developers working with Compass and `compass watch` I'm the only one who doesn't have a problem with watch, all the other devs have the problem that Chris mentioned (works first time).

IIRC the `watch` configuration doesn't trigger for subsequent updates. Like I said I'm the only one who doesn't have this so I'll get the others to comment here.

**Comment by chriseppstein** [comment] 2011-05-24 15:00
Would love to get to the bottom of this. Does uninstalling and re-installing compass, sass, and fssm do the trick? If not it sounds like we have 4 machines that share a common trait here. I will kiss you if you guys can narrow this down to something reproducible so I can fix it.

**Comment by wrumsby** [comment] 2011-05-24 21:49
Our current schedule has us trying to uncover the cause of this in a couple of weeks time. In the meantime we might look at using a TextMate save action, but I will try to collect information about what is going on when we look at our internal issue.

**Comment by wrumsby** [comment] 2011-06-09 03:33
Hi, not sure if this helps, but I created a [Google Docs Spreadsheet](https://spreadsheets.google.com/spreadsheet/ccc?key=0Athz6x4CxSLrdFlsaXFZbWhnSklhRDJLcnpwMDI3cEE&hl=en_US&authkey=CLvVufMO) comparing the `gem local` output of myself and two other developers.

`compass watch` works for me; `compass watch --poll` works for at least one of the other developers, but `compass watch` doesn't.

**Comment by kmiyashiro** [comment] 2011-07-03 06:18
I'm also experiencing this, here's a gist of my gems: http://gist.github.com/1061995

I just did a `gem update` and `gem cleanup` and it is still broken. The only thing I can think of is the latest OS X 10.6.8 update which required a restart. Other than that, nothing has changed.

**Comment by chriseppstein** [comment] 2011-07-03 06:59
I guess someone who's experiencing this issue is going to have to fix it. I can't reproduce it.

**Comment by chriseppstein** [comment] 2011-07-03 18:02
@ttilley, Seriously considering dumping fssm because of this issue. Do you have any advice?

**Comment by ttilley** [comment] 2011-07-03 19:31
@chriseppstein - While that would make me sad, the state of things has changed quite a bit since I wrote FSSM specifically for use in Compass. I've also learned quite a bit from bug reports, interaction with other developers, and eventually needing to dive down to C for rb-fsevent. When I look at the cache implementation in FSSM I can't help but ask myself what kind of drugs I was taking (the problem was deceptively simple, and I never _really_ took into consideration any use cases outside of compass, where directory trees can be deep and expensive to blindly recache in entirety). In short, I'd love to burn the damn thing with fire and write its' replacement from scratch.

Also, as a random example of the crazy issues I've seen and had to deal with, simply installing irbtools breaks everything in rb-fsevent on ruby 1.8.7-p174, but not 1.8.7-p334. No idea why. None.

Mac makes things weird too... any *nix path resolution methods for files under tmp, var, so forth will return paths that start with "/private/" since they're symlinks into that directory. The OSX equivalent APIs specifically try to hide the fact that this directory exists and will strip "/private" from the beginning of any normalized path. This often leads to registering for one path, but receiving events for another path entirely. There are workarounds in there, but weird things still occasionally happen. This isn't a problem with polling, as it doesn't pass through any OSX APIs.

**Comment by ttilley** [comment] 2011-07-03 19:38
Please tell me someone with this issue is using RVM on a mac... If so, then my hope is that reproducing this reliably would just require that person to tarball their ~/.rvm and upload it somewhere. If it can't be reliably reproduced using the -exact- same ruby and gem list then I have no idea what to tell you... but I've had bug reports from a small number of people where events simply weren't firing and after poking spotlight/fseventsd, installing a combo update, or rebooting a few times it just started working. Which is, obviously, insanely frustrating as I then don't know the exact reason it started working and can't write a check for that scenario.

From a previous post of mine on debugging this if you're on a mac using rb-fsevent:

can you all check each volume for /.fseventsd/no_log ? Also, make sure each volume has a /.fseventsd/fseventsd-uuid file containing a UUID of the format:

```
ABC01D2E-F345-6ABC-D7E8-F9AB01C234D5
```

Since I'm not using the volume specific API, it might also just blindly be using the root filesystem settings... That's certainly possible.

Also check to make sure there's an as-root process running called fseventsd (or, more specifically, `/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/CarbonCore.framework/Versions/A/Support/fseventsd`).

I guess also make sure there's a /dev/fsevents ? Looks like it should be mode 0644 with major,minor of 12,6393236.

Also, grep /private/var/log/system.log for 'fseventsd'. Note that "destroying old logs" messages are harmless, and simply mean that the filesystem was modified without that specific fseventsd knowing about it (like... booting into your lion partition on the same drive and having its' spotlight index your snow leopard partition... or what have you). Example:

```
./system.log:Jun 17 15:09:38 Travis-Tilleys-MacBook-Pro fseventsd[20767]: event logs in /.fseventsd out of sync with volume.  destroying old logs. (1 170038 170050)
```

I really really wish I knew what the problem was, specifically, for you guys so that I could write in a check for it and display a helpful warning. Any information is invaluable.

**Comment by ttilley** [comment] 2011-07-03 19:41
@chriseppstein - note that nuking FSSM wouldn't necessarily help if they're seeing the same problem other people are in rb-fsevent. they'd have the same problem with guard or what have you. :-/

**Comment by ttilley** [comment] 2011-07-03 19:44
OH. ALSO. Do any of you have unicode characters in your directory paths being watched? Have you renamed any directories under the path to have the same name but different case? Both scenarios should work, and I've seen work, but have been mentioned.

**Comment by ttilley** [comment] 2011-07-03 19:50
@wrumsby - you're using the polling backend, sarah is using rb-fsevent. James is using the wrong versions of like everything and should be fine after an update (at which point he will also still be using the polling backend like you are though). Is it possible to get a snapshot of sarah's ~/.rvm/ if she is using rvm? I know that it might be a bit much to ask, but it would help me immensely.

Also, is she using OSX 10.5.x or 10.6.x? Xcode 3.2.x or 4.0.x? Or even 4.1.x or 4.2.x for iOS beta work?

**Comment by ttilley** [comment] 2011-07-03 20:05
I actually think that the person who mentioned "a few reboots" fixing it might have booted into another install of OSX, made changes, and then back into the main OSX install. This would have triggered an inconsistent history event, since changes were made that the installed fseventsd wasn't aware of, resulting in the previous logs being thrown out and state being rebuilt. This may have included various other forms of housekeeping that resulted in fseventsd simply fixing itself.

**Comment by wrumsby** [comment] 2011-07-04 00:47
@ttilley Just had a look, Sarah doesn't seem to be using rvm - she should have a fairly standard OS X environment (unless Coda installs additional things).

**Comment by chriseppstein** [comment] 2011-07-04 00:55
@ttilley I appreciate that this is a hard problem and thanks for your hard work on it. I'm fine with there being a predetermined checklist for users to run thru if they are having problems before escalating this to a bug and getting you involved. Maybe a wiki page could be constructed or perhaps this issue could perhaps be boiled down to a script that checks for issues and returns a list of conflicts/warnings based on your system.

Regarding the desire to burn things to the ground and start over, I know that feeling well. But do be careful :)

**Comment by ttilley** [comment] 2011-07-04 01:32
@wrumsby - what versions of OSX and Xcode? Also, does anything from the previous checklist stand out?

**Comment by wrumsby** [comment] 2011-07-04 01:52
@ttilley She has OS X 10.6.8 and XCode 3.2.6 (1761).

The `watch` is watching a subdirectory of her `/Users/` directory. Watch _is_ working for `.scss` files, but isn't picking up changes to other files defined in a `watch` config in `config.rb`.

The fseventsd process appears to be running correctly and `/dev/fsevents` is there, but there's nothing if she runs

```
grep 'fsevent' /private/var/log/system.log
```

**Comment by ESWAT** [comment] 2011-07-11 15:35
Hi, just wanted to chime in that I’ve also started having this problem today and had to switch to the polling method. I was on Compass 11.4 and after updating my gems and Compass to 11.5 was still having problems.

Gemset (1.9.2@180 with RVM) https://gist.github.com/1076049
.gemrc https://github.com/eswat/osx-dotfiles/blob/master/gemrc
Tarball of my .rvm http://dl.dropbox.com/u/506504/rvm.tar.gz

Running OSX 10.6.8 with Xcode 3.2.4. I was making some modifications to my dotfiles yesterday so I might have changed something fssm didn’t like? Not really sure.

**Comment by ttilley** [comment] 2011-07-12 00:06
Awesome. Well, the rvm bundle, not you having issues. ^^;

If I can't reproduce this using the same exact binaries, I'm taking a
double shot for every comment.

On Monday, July 11, 2011, eswat
reply@reply.github.com
wrote:

> Hi, just wanted to chime in that I’ve also started having this problem today and had to switch to the polling method. I was on Compass 11.4 and after updating my gems and Compass to 11.5 was still having problems.
> 
> Gemset (1.9.2@180 with RVM) https://gist.github.com/1076049
> .gemrc https://github.com/eswat/osx-dotfiles/blob/master/gemrc
> Tarball of my .rvm http://dl.dropbox.com/u/506504/rvm.tar.gz
> 
> Running OSX 10.6.8 with Xcode 3.2.4. I was making some modifications to my dotfiles yesterday so I might have changed something fssm didn’t like? Not really sure.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/chriseppstein/compass/issues/394#issuecomment-1547326

## 
-               *
  Travis Tilley
  (201)676-0873

**Comment by ttilley** [comment] 2011-07-12 12:31
actually, it might be a bit until I have a solid time slot for this. I wish it were painless to install OSX into a virtual machine... Since I have a mac dev account, I -can- install osx server into a virtual machine for dev purposes, which they allow... then set it up with exactly the right version of xcode and whatnot.

my main system is currently running the GM seed of lion and xcode <4.1 isn't even available.

actually, that's exactly what i'm going to do: install osx snow leopard server in virtualbox using the developer use serial key, and go from there. there shouldn't be any toolchain differences that would effect anything, but there certainly will be differences that will be frustrating. the presence of distributed spotlight alone might make enough of a difference to negate its' usefulness. :-/

**Comment by ttilley** [comment] 2011-07-15 22:58
@chriseppstein - I'm thinking it might be best to default to polling in FSSM on mac for a while. The issue is potentially within fsevents itself if it's the issue stated within the context of Time Machine last month on Apple's filesystem-dev list.

If your watch functionality is broken, and calling rb-fsevent from that same path is similarly broken, but watching from that path's direct parent works without anything else having changed... then congratulations, you've hit the bug I'm describing. It can be worked around by (prepare yourself for it) renaming the directory, watching the event stream from that root, changing something, stopping the event stream, and giving the directory its original name.

The above is exactly the workaround accidentally discovered by @bquorning https://github.com/thibaudgg/rb-fsevent/issues/10#issuecomment-1578378

**Comment by chibisov** [comment] 2011-07-18 05:37
I have the same issue only if workin in Dropbox folder.

**Comment by ttilley** [comment] 2011-08-24 19:14
I can't reproduce this bug locally, and everyone who reports it to the rb-fsevent issue tracker seems to magically fix it at some later point by upgrading xcode, tweaking a setting, or something entirely unrelated. I have an open ticket with apple hoping to get a few details clarified (especially regarding the new, but essentially undocumented, file-level events).

This hasn't been dropped or ignored. I've even asked for people to meet up on IRC and let me poke around to debug a system where this issue still occurs, but every time before I get a chance something unrelated is done and the bug goes away.

I think the next major version of rb-fsevent will come with a pre-compiled fsevent_watch in part to slim down the number of potential variables to something I can deal with. As a result I've added runtime feature detection, a compatibility shim, etc so that a binary compiled on lion with the 10.7 SDK will run essentially the same as one compiled on leopard against the 10.5 SDK on leopard, snow leopard, and lion with no loss/change in functionality outside of what the OS provides (hopefully with sane and useful error messages).

Experimental pre-built one-off for getting feedback: https://github.com/ttilley/rb-fsevent/tree/pre-compiled-gem-one-off

New standalone fsevent_watch repo: https://github.com/ttilley/fsevent_watch

**Comment by stevepiercy** [comment] 2011-08-24 22:10
@ttilley what is the IRC channel or handle to troubleshoot in real-time? If I had known about how to get help in real-time, I would have jumped at the chance.

I had this issue on 10.5, and like kmiyashiro above, after an OS update and a restart, the problem has gone away.
https://github.com/chriseppstein/compass/issues/394#issuecomment-1491511

**Comment by ttilley** [comment] 2011-08-24 22:58
I'm usually on irc.freenode.net as either Aphelion or ttilley (though more often idle than not). I suppose the best channel for anything rb-fsevent specific would be #guard rather than #compass.

**Comment by dangayle** [comment] 2011-12-22 22:19
I'm having the works once, then stops issue with --watch also. Using --poll works. Using latest everything on OSX 10.7.2

**Comment by e-anima** [comment] 2012-02-20 14:52
i have thhe problem too that sass watch is working and compass watch is not. i guess it is because i run a vm and mount the drive inside.
my quick fix is a linux command calling compass watch . every second.
while sleep 1; do compass compile . ;done

**Comment by chriseppstein** [comment] 2012-02-20 20:24
You can try `compass watch --poll` which basically does what you're script here does.

**Comment by burabure** [comment] 2013-02-21 23:18
I've noticed that Cloud storage systems like dropbox and sugarsync can interfere in the way compass watches file changes. I have to turn them off for compass to catch all my modifications

**Comment by kyleskrinak** [comment] 2013-02-23 16:53
I am having this issue. Specifics: MacOSX 10.7.5; ruby 1.9.3p392 (2013-02-22 revision 39386) [x86_64-darwin11.4.2], rvm 1.18.10, compass (0.12.2), fssm (0.2.10) FWIW, I don't have this problem on my ubuntu systems. My temporary better-than-nothing fix is to move all imported files into the same directory.

**Comment by scottdavis** [comment] 2013-03-01 22:28
this is fixed in the master branch

**Closed as completed** 2013-03-01 22:28 UTC
Labels: compass core, Test after listen integration

**Comment by sethkrasnianski** [comment] 2013-11-27 23:11
I'm experiencing this right now with
`Sass 3.2.12 (Media Mark)`
`Compass 0.12.2 (Alnilam)`

`compass watch --poll` only works not `compass watch`

**Comment by evilive3000** [comment] 2014-04-12 16:03
doesn't detect changes! But detects syntax error.
Example: 

```
>>> Compass is polling for changes. Press Ctrl-C to Stop.
>>> Change detected at 21:01:41 to: screen.scss
    error sass/screen.scss (Line 207: Invalid CSS after "...r_music/index";": expected "}", was "")
overwrite ../screen.css
```

```
$ gem list
*** LOCAL GEMS ***
chunky_png (1.3.0)
compass (0.12.5)
fssm (0.2.10)
sass (3.2.19)

$ ruby -v
ruby 1.9.3p194 (2012-04-20 revision 35410) [x86_64-linux]
```

`--poll` doesn't help.

**Comment by sktzoootech** [comment] 2014-05-02 01:41
Hi there,

I also experience this problem.  When I do a compass watch.  Nothing happens, not even an error. It's like its frozen but I can ctrl+c to exit.  Not a hint why it doesn't work. Below are the details and versions I am using:
sass - (3.3.6)
compass - (1.0.0.alpha.19)
susy - (2.1.2)

ruby: 1.9.3p125

**Comment by lolmaus** [comment] 2014-05-02 09:16
Try `compass clean`.

**Comment by Arduinology** [comment] 2014-08-20 16:24
EDIT: Nevermind, I was doing compass watch from inside a Vagrant SSH. Turns out I had to 'compass watch' from the host OS. Works as intended.

I am experiencing this problem. No errors,  no warning, just doesn't work.

Sass 3.2.12 (Media Mark)
Compass 0.12.2 (Alnilam)
ruby 1.9.3p547 (2014-05-14 revision 45962) [x86_64-linux]

**Comment by Stefadesign** [comment] 2014-09-02 18:12
Same in here. Just installed it on WIN 8 and same issue, initially it renders CSS file but "watch" is not working... I am running WIN8 x64 if that helps...

**Comment by asso1985** [comment] 2014-09-03 10:14
Same here : initially renders the CSS file but "watch" is not working

**Comment by HadrienMP** [comment] 2014-09-05 20:42
Same too. I tried on Windows 8 and on a clean ubuntu installation

**Comment by jeromecovington** [comment] 2014-10-08 20:11
I am experiencing this issue as well. Running "compass watch" generates initial CSS files but does not update with changes to the scss files. There is no output to the terminal following the initial CSS files generation. I am working using Ubuntu 12.04.5 LTS via the Codio cloud IDE with the following.
Sass 3.4.5 (Selective Steve)
Compass 1.0.1 (Polaris)

Update: After restarting the Codio environment, "compass watch" worked as expected.

**Comment by zquintana** [comment] 2014-10-20 21:03
Just ugraded to Max OS X Yosemite and now I'm having this problem. Only does first compile after I run clean, after that, nothing. Never watches even.

**Comment by aaronbushnell** [comment] 2014-10-27 19:26
Having this error inside my Vagrant setup running Ubuntu 12.04. Using `compass watch` compiles everything and then doesn't re-compile on a change, but `compass watch --poll` works.

Current gems:

```
bigdecimal (1.2.5, 1.1.0)
bundler (1.7.4, 1.6.2)
bundler-unload (1.0.2)
chunky_png (1.3.3)
compass (1.0.1)
compass-core (1.0.1)
compass-import-once (1.0.5)
executable-hooks (1.3.2)
ffi (1.9.6)
fssm (0.2.10)
gem-wrappers (1.2.7, 1.2.4)
io-console (0.4.2, 0.3)
json (1.8.1, 1.5.5)
minitest (5.4.2, 2.5.1)
multi_json (1.10.1)
rake (10.3.2, 0.9.2.2)
rb-fsevent (0.9.4)
rb-inotify (0.9.5)
rdoc (4.1.2, 3.9.5)
rubygems-bundler (1.4.4)
rubygems-update (2.4.2)
rvm (1.11.3.9)
sass (3.4.6, 3.4.0)
```

Ruby version `ruby 1.9.3p547`

**Update**: Looks like this is an issue with Sass itself if you are running the command within Vagrant. https://github.com/sass/sass/issues/504

**Comment by foxx** [comment] 2014-11-14 22:13
@wrumsby I can confirm that `--poll` works for me (thank you). 

My use case is using a shared folder in Vagrant via VirtualBox, which is then shared with a Docker container inside the VM, which seems to use `vboxsf`

**Comment by davidrichied** [comment] 2016-02-21 20:33
Compass 1.0.3
Sass 3.4.21
Vagrant 1.8.1
Vagrant Box: VVV
OS: Mac 10.11.2
Inside of VVV (after entering it with `vagrant ssh`), `compass watch` does not update .css file when I save .scss file, but `compass watch --poll` does. I have not tried using Compass outside of VVV, but I am sure it would work.

**Comment by mrugeshrocks** [comment] 2016-06-18 05:42
In my case, i was Using winscp for file transfer.
Compass watch didnot detect any changes in modified.

Updated gems and compass also used --poll but still did not work.
After hours of debugging found that winscp was preserving the file timestamp and that was causing the issue. 

To fix that : 
1) In your WinSCP go to Option -> Preferences -> Transfer
2) Edit the preset you are using
3) Uncheck the preserve timestamp option.

That's it!! And it started detecting changes.
