### ISSUE TITLE
compass watch broken

### ISSUE THREAD

**Issue by jjmalina** [Compass/compass#719] opened 2012-02-14 18:06 UTC
Hi,

I'm running compass 0.11.5 and Sass 3.1.15 and in one of my projects I'm unable to run `compass watch` instead I have to constantly run `compass compile` which works successfully though it displays the same error at the end.

This is the error I'm getting:

```
Jeremiah-Malinas-MacBook-Pro:muckrack jmalina$ compass watch
SystemStackError on line 413 of /Users/jmalina/.gem/ruby/1.8/gems/sass-3.1.15/lib/sass/../sass/script/parser.rb: stack level too     deep
Run with --trace to see the full backtrace
```

It seems like a Sass issue but I'm not really sure what to do about it. Would appreciate some advice.

Thanks,

Jeremiah

**Comment by chriseppstein** [comment] 2012-02-14 21:00
Can you please `Run with --trace to see the full backtrace`?

**Comment by jjmalina** [comment] 2012-02-14 21:09
Sure, it's really long so I pasted it at http://pastebin.com/qdmdzAMt

**Comment by chriseppstein** [comment] 2012-02-14 21:14
@nex3 Sass bug?

@jmalina327 Can you get this down to a minimal sass file or compass project that we can use to reproduce it?

**Comment by nex3** [comment] 2012-02-14 23:30
Probably a Sass bug, yes. Please post an issue on the [Sass tracker](/nex3/sass/issues) once you have a reduced repro case.

**Comment by jjmalina** [comment] 2012-02-15 01:03
I found that this is related to compass' sprite generation. I'll investigate a bit more and will post on the Sass repo.

**Comment by ZeeAgency** [comment] 2012-02-27 09:48
Same thing, it looks like there's a memory limit related to sprite generation around 2Mo (120 PNG x ~16Ko each)

**Comment by chriseppstein** [comment] 2012-02-27 17:29
@jmalina327 @ZeeAgency In these cases the generated sprite file gets _really_ big. Suggest you use the sprite file generator `compass sprite --skip-overrides "sprite_folder/*.png"`

**Comment by chriseppstein** [comment] 2012-03-12 07:08
closing -- I'm assuming the pregeneration of sprite files cleared this up for you.

**Closed as completed by chriseppstein** 2012-03-12 07:08 UTC
