### ISSUE TITLE
Segmentation fault on file change

### ISSUE THREAD

**Issue by palosopko** [Compass/compass#295] opened 2011-03-05 23:17 UTC
When I tried Mac OS Lion Developer Preview `compass` didn't work properly. Watch started alright but once you save a file it fails with a segmentation fault:

```
$ compass watch -c compass.rb
>>> Change detected to: .../screen.scss
overwrite .../screen.css 
>>> Compass is watching for changes. Press Ctrl-C to Stop.
/Library/Ruby/Gems/1.8/gems/compass-0.11.beta.2/lib/vendor/fssm/fssm/backends/fsevents.rb:27: [BUG] Segmentation fault
ruby 1.8.7 (2010-01-10 patchlevel 249) [universal-darwin11.0]

Abort trap: 6
```

**Comment by scottdavis** [comment] 2011-03-06 21:14
I don't think anyone has a copy of lion that works on compass but your more then welcome to supply a patch

**Comment by scottdavis** [comment] 2011-03-06 21:15
also this is more of an FSSM bug

**Comment by chriseppstein** [comment] 2011-04-02 17:11
dupe of #288.

**Closed as completed by chriseppstein** 2011-04-02 17:11 UTC
