### ISSUE TITLE
-q, --quiet Are not working for compass compile

### ISSUE THREAD

**Issue by fantactuka** [Compass/compass#388] opened 2011-05-12 23:19 UTC
Event if running `compass compile -q` or `compass compile --quiet` it still output compiling info into console, like "identical ../display.css" 

Tried with compass (0.11.1)

Is there another way to make it completely quiet?

**Comment by chriseppstein** [comment] 2011-07-03 07:31
I'm pretty sure this is fixed now. I did some work on this recently and I can't reproduce it now. Please try again with compass  0.11.4

**Closed as completed by chriseppstein** 2011-07-03 07:31 UTC
Labels: command line, unverified bug

**Comment by fantactuka** [comment] 2011-07-03 07:37
I've found smth like options[:loud] that contains [:identical, :create, :override] at Compass::Actions.log_action and in case this option is defined - quiet will be overridden to `false`. I was looking for a way to set :loud to `[]` or `nil` when using command line but didn't find it.

**Comment by chriseppstein** [comment] 2011-07-03 07:52
But I thought those are only loud when using the watcher. At least that was what I intended.

**Comment by fantactuka** [comment] 2011-07-03 08:04
Actually you was right. Updated to 0.11.4 and it looks fine now. 
Thanks a lot for compass
