### ISSUE TITLE
Support for HSL(a)/RGBA(a) colors as mixin parameters

### ISSUE THREAD

**Issue by bbodien** [Compass/compass#204] opened 2010-10-06 02:02 UTC
Currently you can't pass color values specified in the HSL, HSLA, RGB, or RGBA color models as parameters to Compass mixins such as box-shadow, because each of these color models uses comma separation between the channel values.

It would be great if we could wrap these color representations in quotes to have the commas within them ignored, and not interpreted by SASS as parameter separators, for example:

@include box-shadow(1px, 1px, 1px, "rgba(0,0,0,0.5)");

**Comment by mirisuzanne** [comment] 2010-10-06 07:22
I don't think this is accurate. Have you tried it? This works fine for me in both syntaxes without the quotes.

**Comment by bbodien** [comment] 2010-10-06 15:56
Interesting to hear it works for you. I shall do more extensive testing and report back.

**Comment by chriseppstein** [comment] 2010-10-11 08:05
I cannot reproduce this either. Closing.

**Closed as completed by chriseppstein** 2010-10-11 08:05 UTC
