### ISSUE TITLE
Bug with repeat-x

### ISSUE THREAD

**Issue by aurelien-baudet** [Compass/compass#296] opened 2011-03-08 10:44 UTC
Hi,

I have a sprite with many images and not with the same size. The width of the generated sprite is 1024px. I have a 22px image that I want to put in this sprite and repeat it horizontally. I used the variable
    $<map>-<sprite>-repeat: repeat-x;
as described in the documentation but I got the error:
    ChunkyPNG::OutOfBounds on line ["233"] of D: Background image width is too small!

stack:

<pre>
D:/Applications/developpement/Ruby/lib/ruby/gems/1.9.1/gems/chunky_png-0.12.0/lib/chunky_png/canvas/operations.rb:48:in `replace'
D:/Applications/developpement/Ruby/lib/ruby/gems/1.9.1/gems/compass-0.11.beta.2/lib/compass/sass_extensions/functions/sprites.rb:153:in `block in construct_sprite'
D:/Applications/developpement/Ruby/lib/ruby/gems/1.9.1/gems/compass-0.11.beta.2/lib/compass/sass_extensions/functions/sprites.rb:146:in `each'
D:/Applications/developpement/Ruby/lib/ruby/gems/1.9.1/gems/compass-0.11.beta.2/lib/compass/sass_extensions/functions/sprites.rb:146:in `construct_sprite'
D:/Applications/developpement/Ruby/lib/ruby/gems/1.9.1/gems/compass-0.11.beta.2/lib/compass/sass_extensions/functions/sprites.rb:126:in `generate'
D:/Applications/developpement/Ruby/lib/ruby/gems/1.9.1/gems/compass-0.11.beta.2/lib/compass/sass_extensions/functions/sprites.rb:294:in `sprite_url'
D:/Applications/developpement/Ruby/lib/ruby/gems/1.9.1/gems/compass-0.11.beta.2/lib/compass/sass_extensions/functions/sprites.rb:220:in `method_missing'
D:/Applications/developpement/Ruby/lib/ruby/gems/1.9.1/gems/compass-0.11.beta.2/lib/compass/sass_extensions/functions/sprites.rb:211:in `to_s'
D:/Applications/developpement/Ruby/lib/ruby/gems/1.9.1/gems/sass-3.1.0.alpha.221/lib/sass/script/list.rb:36:in `block in to_s'
D:/Applications/developpement/Ruby/lib/ruby/gems/1.9.1/gems/sass-3.1.0.alpha.221/lib/sass/script/list.rb:36:in `map'
D:/Applications/developpement/Ruby/lib/ruby/gems/1.9.1/gems/sass-3.1.0.alpha.221/lib/sass/script/list.rb:36:in `to_s'
D:/Applications/developpement/Ruby/lib/ruby/gems/1.9.1/gems/sass-3.1.0.alpha.221/lib/sass/tree/visitors/perform.rb:217:in `visit_prop'
D:/Applications/developpement/Ruby/lib/ruby/gems/1.9.1/gems/sass-3.1.0.alpha.221/lib/sass/tree/visitors/base.rb:37:in `visit'
D:/Applications/developpement/Ruby/lib/ruby/gems/1.9.1/gems/sass-3.1.0.alpha.221/lib/sass/tree/visitors/perform.rb:18:in `visit'
D:/Applications/developpement/Ruby/lib/ruby/gems/1.9.1/gems/sass-3.1.0.alpha.221/lib/sass/tree/visitors/base.rb:53:in `block in visit_children'
D:/Applications/developpement/Ruby/lib/ruby/gems/1.9.1/gems/sass-3.1.0.alpha.221/lib/sass/tree/visitors/base.rb:53:in `map'
D:/Applications/developpement/Ruby/lib/ruby/gems/1.9.1/gems/sass-3.1.0.alpha.221/lib/sass/tree/visitors/base.rb:53:in `visit_children'
D:/Applications/developpement/Ruby/lib/ruby/gems/1.9.1/gems/sass-3.1.0.alpha.221/lib/sass/tree/visitors/perform.rb:27:in `block in visit_children'
D:/Applications/developpement/Ruby/lib/ruby/gems/1.9.1/gems/sass-3.1.0.alpha.221/lib/sass/tree/visitors/perform.rb:39:in `with_environment'
D:/Applications/developpement/Ruby/lib/ruby/gems/1.9.1/gems/sass-3.1.0.alpha.221/lib/sass/tree/visitors/perform.rb:26:in `visit_children'
D:/Applications/developpement/Ruby/lib/ruby/gems/1.9.1/gems/sass-3.1.0.alpha.221/lib/sass/tree/visitors/base.rb:37:in `block in visit'
D:/Applications/developpement/Ruby/lib/ruby/gems/1.9.1/gems/sass-3.1.0.alpha.221/lib/sass/tree/visitors/perform.rb:232:in `visit_rule'
D:/Applications/developpement/Ruby/lib/ruby/gems/1.9.1/gems/sass-3.1.0.alpha.221/lib/sass/tree/visitors/base.rb:37:in `visit'
D:/Applications/developpement/Ruby/lib/ruby/gems/1.9.1/gems/sass-3.1.0.alpha.221/lib/sass/tree/visitors/perform.rb:18:in `visit'
D:/Applications/developpement/Ruby/lib/ruby/gems/1.9.1/gems/sass-3.1.0.alpha.221/lib/sass/tree/visitors/perform.rb:138:in `block in visit_import'
D:/Applications/developpement/Ruby/lib/ruby/gems/1.9.1/gems/sass-3.1.0.alpha.221/lib/sass/tree/visitors/perform.rb:138:in `map'
D:/Applications/developpement/Ruby/lib/ruby/gems/1.9.1/gems/sass-3.1.0.alpha.221/lib/sass/tree/visitors/perform.rb:138:in `visit_import'
D:/Applications/developpement/Ruby/lib/ruby/gems/1.9.1/gems/sass-3.1.0.alpha.221/lib/sass/tree/visitors/base.rb:37:in `visit'
D:/Applications/developpement/Ruby/lib/ruby/gems/1.9.1/gems/sass-3.1.0.alpha.221/lib/sass/tree/visitors/perform.rb:18:in `visit'
D:/Applications/developpement/Ruby/lib/ruby/gems/1.9.1/gems/sass-3.1.0.alpha.221/lib/sass/tree/visitors/perform.rb:138:in `block in visit_import'
D:/Applications/developpement/Ruby/lib/ruby/gems/1.9.1/gems/sass-3.1.0.alpha.221/lib/sass/tree/visitors/perform.rb:138:in `map'
D:/Applications/developpement/Ruby/lib/ruby/gems/1.9.1/gems/sass-3.1.0.alpha.221/lib/sass/tree/visitors/perform.rb:138:in `visit_import'
D:/Applications/developpement/Ruby/lib/ruby/gems/1.9.1/gems/sass-3.1.0.alpha.221/lib/sass/tree/visitors/base.rb:37:in `visit'
D:/Applications/developpement/Ruby/lib/ruby/gems/1.9.1/gems/sass-3.1.0.alpha.221/lib/sass/tree/visitors/perform.rb:18:in `visit'
D:/Applications/developpement/Ruby/lib/ruby/gems/1.9.1/gems/sass-3.1.0.alpha.221/lib/sass/tree/visitors/base.rb:53:in `block in visit_children'
D:/Applications/developpement/Ruby/lib/ruby/gems/1.9.1/gems/sass-3.1.0.alpha.221/lib/sass/tree/visitors/base.rb:53:in `map'
D:/Applications/developpement/Ruby/lib/ruby/gems/1.9.1/gems/sass-3.1.0.alpha.221/lib/sass/tree/visitors/base.rb:53:in `visit_children'
D:/Applications/developpement/Ruby/lib/ruby/gems/1.9.1/gems/sass-3.1.0.alpha.221/lib/sass/tree/visitors/perform.rb:27:in `block in visit_children'
D:/Applications/developpement/Ruby/lib/ruby/gems/1.9.1/gems/sass-3.1.0.alpha.221/lib/sass/tree/visitors/perform.rb:39:in `with_environment'
D:/Applications/developpement/Ruby/lib/ruby/gems/1.9.1/gems/sass-3.1.0.alpha.221/lib/sass/tree/visitors/perform.rb:26:in `visit_children'
D:/Applications/developpement/Ruby/lib/ruby/gems/1.9.1/gems/sass-3.1.0.alpha.221/lib/sass/tree/visitors/base.rb:37:in `block in visit'
D:/Applications/developpement/Ruby/lib/ruby/gems/1.9.1/gems/sass-3.1.0.alpha.221/lib/sass/tree/visitors/perform.rb:47:in `visit_root'
D:/Applications/developpement/Ruby/lib/ruby/gems/1.9.1/gems/sass-3.1.0.alpha.221/lib/sass/tree/visitors/base.rb:37:in `visit'
D:/Applications/developpement/Ruby/lib/ruby/gems/1.9.1/gems/sass-3.1.0.alpha.221/lib/sass/tree/visitors/perform.rb:18:in `visit'
D:/Applications/developpement/Ruby/lib/ruby/gems/1.9.1/gems/sass-3.1.0.alpha.221/lib/sass/tree/visitors/perform.rb:7:in `visit'
D:/Applications/developpement/Ruby/lib/ruby/gems/1.9.1/gems/sass-3.1.0.alpha.221/lib/sass/tree/root_node.rb:20:in `render'
D:/Applications/developpement/Ruby/lib/ruby/gems/1.9.1/gems/sass-3.1.0.alpha.221/lib/sass/engine.rb:302:in `_render'
D:/Applications/developpement/Ruby/lib/ruby/gems/1.9.1/gems/sass-3.1.0.alpha.221/lib/sass/engine.rb:250:in `block in render'
D:/Applications/developpement/Ruby/lib/ruby/gems/1.9.1/gems/sass-3.1.0.alpha.221/lib/sass/util.rb:298:in `silence_sass_warnings'
D:/Applications/developpement/Ruby/lib/ruby/gems/1.9.1/gems/sass-3.1.0.alpha.221/lib/sass/engine.rb:250:in `render'
D:/Applications/developpement/Ruby/lib/ruby/gems/1.9.1/gems/compass-0.11.beta.2/lib/compass/compiler.rb:117:in `block (2 levels) in compile'
D:/Applications/developpement/Ruby/lib/ruby/gems/1.9.1/gems/compass-0.11.beta.2/lib/compass/compiler.rb:103:in `timed'
D:/Applications/developpement/Ruby/lib/ruby/gems/1.9.1/gems/compass-0.11.beta.2/lib/compass/compiler.rb:116:in `block in compile'
D:/Applications/developpement/Ruby/lib/ruby/gems/1.9.1/gems/compass-0.11.beta.2/lib/compass/logger.rb:45:in `red'
D:/Applications/developpement/Ruby/lib/ruby/gems/1.9.1/gems/compass-0.11.beta.2/lib/compass/compiler.rb:115:in `compile'
D:/Applications/developpement/Ruby/lib/ruby/gems/1.9.1/gems/compass-0.11.beta.2/lib/compass/compiler.rb:95:in `compile_if_required'
D:/Applications/developpement/Ruby/lib/ruby/gems/1.9.1/gems/compass-0.11.beta.2/lib/compass/compiler.rb:82:in `block (2 levels) in run'
D:/Applications/developpement/Ruby/lib/ruby/gems/1.9.1/gems/compass-0.11.beta.2/lib/compass/compiler.rb:80:in `each'
D:/Applications/developpement/Ruby/lib/ruby/gems/1.9.1/gems/compass-0.11.beta.2/lib/compass/compiler.rb:80:in `block in run'
D:/Applications/developpement/Ruby/lib/ruby/gems/1.9.1/gems/compass-0.11.beta.2/lib/compass/compiler.rb:103:in `timed'
D:/Applications/developpement/Ruby/lib/ruby/gems/1.9.1/gems/compass-0.11.beta.2/lib/compass/compiler.rb:79:in `run'
D:/Applications/developpement/Ruby/lib/ruby/gems/1.9.1/gems/compass-0.11.beta.2/lib/compass/commands/watch_project.rb:110:in `recompile'
D:/Applications/developpement/Ruby/lib/ruby/gems/1.9.1/gems/compass-0.11.beta.2/lib/compass/commands/watch_project.rb:40:in `perform'
D:/Applications/developpement/Ruby/lib/ruby/gems/1.9.1/gems/compass-0.11.beta.2/lib/compass/commands/base.rb:18:in `execute'
D:/Applications/developpement/Ruby/lib/ruby/gems/1.9.1/gems/compass-0.11.beta.2/lib/compass/commands/project_base.rb:19:in `execute'
D:/Applications/developpement/Ruby/lib/ruby/gems/1.9.1/gems/compass-0.11.beta.2/lib/compass/exec/sub_command_ui.rb:43:in `perform!'
D:/Applications/developpement/Ruby/lib/ruby/gems/1.9.1/gems/compass-0.11.beta.2/lib/compass/exec/sub_command_ui.rb:15:in `run!'
D:/Applications/developpement/Ruby/lib/ruby/gems/1.9.1/gems/compass-0.11.beta.2/bin/compass:25:in `block in <top (required)>'
D:/Applications/developpement/Ruby/lib/ruby/gems/1.9.1/gems/compass-0.11.beta.2/bin/compass:39:in `call'
D:/Applications/developpement/Ruby/lib/ruby/gems/1.9.1/gems/compass-0.11.beta.2/bin/compass:39:in `<top (required)>'
D:/Applications/developpement/Ruby/bin/compass:19:in `load'
D:/Applications/developpement/Ruby/bin/compass:19:in `<main>'
</pre>

**Comment by chriseppstein** [comment] 2011-03-08 18:01
Hi Nico, could you investigate this?

**Comment by scottdavis** [comment] 2011-03-29 02:47
can you try this using the compass 0.11.beta.5?

**Comment by aurelien-baudet** [comment] 2011-03-29 09:17
Hi!

I've just tested with 0.11.beta.5 and it still fails with this error:
       ChunkyPNG::OutOfBounds on line ["282"] of D: Background image width is too small!

**Comment by scottdavis** [comment] 2011-03-29 18:50
im not really sure whats going on here maybe @wvanbergen can give some input

**Comment by wvanbergen** [comment] 2011-03-29 19:06
Can you give a backtrace with ChunkyPNG 1.0 or 1.1?

**Comment by scottdavis** [comment] 2011-03-29 19:10
The beta compass is using 1.1

**Comment by wvanbergen** [comment] 2011-03-29 19:24
The backtrace available here still used ChunkyPNG 0.12. That' why I asked for a new backtrace.

**Comment by aurelien-baudet** [comment] 2011-03-30 10:00
I made a sample in order to reproduce it easily. It seems that the bug happens when the repeated sprite image is not a multiple of the whole image. Example:

<table>
<thead>
<tr><th>total width</th><th>sprite width</th><th>total width/sprite width</th><th>result</th></tr>
</thead>
<tbody>
<tr><td>1280</td><td>16</td><td>80</td><td><b>OK</b></td></tr>
<tr><td>1280</td><td>26</td><td>49,23076923076923</td><td><b>KO</b></td></tr>
</tbody>
</table>


The sample to reproduce it: http://www.2shared.com/file/cIXwaDZp/compass.html

**Comment by scottdavis** [comment] 2011-03-30 13:36
So I think the solution from at least the compass end should be to die gracefully. Unless @wvanbergen thinks this is a valid chunky png bug.

**Comment by wvanbergen** [comment] 2011-03-30 13:47
ChunkyPNG raises that particular error when there is not enough space to paste the image on the background image, so this most likely occurs with the very final sprite image near the edge of the background image. 

This is not a bug in ChunkyPNG. To resolve the issue, I could add a method that will silently ignore all the pixels that fall off the background image when pasting, or this can be solved on Compass's end, by cutting off the pixels that will no longer fit on the background before pasting.

**Comment by scottdavis** [comment] 2011-03-30 15:16
I wouldn't modify your api for this it seems like a necessary error. I'll make some modifications to the sprite generation engine to calculate the dimensions correctly.

**Comment by scottdavis** [comment] 2011-03-30 15:19
also thanks @wvanbergen for your input

**Comment by scottdavis** [comment] 2011-04-01 18:47
closed by 2c62cdf2f96c2f769faaf03f86cb28815984d963 rescue OutOfBounds exception gracfuly

**Closed as completed by scottdavis** 2011-04-01 18:47 UTC
Labels: feature request, bug, compass core, documentation, needs patch

**Comment by vbichkovsky** [comment] 2011-11-28 18:31
I've just stumbled on this issue today. Okay, I don't get an exception, but my repeat-x image has a gap, as it doesn't fill the sprite horizontally. To fix the issue, I just changed the code which calculates sprite's width.
I'm going to make a pull request with my commit.
