### ISSUE TITLE
Deprecation warnings everywhere

### ISSUE THREAD

**Issue by marcandre** [Compass/compass#128] opened 2010-05-07 17:27 UTC
Hi!

I'm trying to upgrade to 0.10.rc5, but I have 4 (maybe related) problems.

1) I get warnings I can't seem to fix. Ex:

WARNING: DEPRECATED: Please change your @import of compass.sass to: @import "compass"
        on line 1 of /Library/Ruby/Gems/1.8/gems/compass-0.10.0.rc5/frameworks/_compass_deprecated_imports/stylesheets/./_compass.sass
        from line 48 of an unknown file

Note the "unknown file". Presuming it is my screen.sass, line 48 reads:
  @import "compass"

What exactly am I supposed to do?

2) No idea why, but the reset css, included first in my screen.sass, doesn't show in the css. The @import "blueprint/reset" line didn't generate warnings.

3) Minor, but annoying: some warnings are for imports I didn't directly import... so there is no way to fix them and I get way more warning than I should. It makes it harder to know what I might be doing wrong. Ex:
WARNING: DEPRECATED: Please change your @import of compass/utilities/general/clearfix.sass to: @import "compass/utilities/general/clearfix"
        on line 1 of /Library/Ruby/Gems/1.8/gems/compass-0.10.0.rc5/frameworks/_compass_deprecated_imports/stylesheets/compass/utilities/general/_clearfix.sass
        from line 19 of an unknown file
        from line 1 of an unknown file
        from line 11 of an unknown file

My line 11 is @import "blueprint/scaffolding"

**Comment by chriseppstein** [comment] 2010-05-07 22:02
I'll need to fix the bug about warning not knowing what file they are coming from. That's super annoying.

I wonder if this is a bug related to the sass-cache. Can you run `rm -rf .sass-cache` and see if the issue goes away, it looks to me that you have made the required changes. But again, without file names, it's really hard to say. Can you please provide the following information so I can try to reproduce this issue:
1. What OS & OS Version?
2. How are you running compass? Are you using any frameworks with it?

**Comment by chriseppstein** [comment] 2010-05-09 06:36
Ok. So the way compass is handling the migration to scss is by keeping all the sass files in a different load path entry that comes later than the entry with the scss files. In rails projects, compass configures sass and tells it all the load paths, but it passes it as a hash, and insertion order of a hash is not maintained in some older versions of ruby. This is why Sass allows passing an array of tuples instead of a hash, so I was able to fix this bug by changing how I pass the stylesheet paths to sass.

**Comment by chriseppstein** [comment] 2010-05-09 06:57
[Rails] Pass template locations as an array of tuples instead of as a hash to preserve load path ordering.
Closed by 5d0454dc022813884aad5208923c5cd2b954366b.

**Closed as completed by chriseppstein** 2010-05-09 06:57 UTC

**Comment by marcandre** [comment] 2010-05-10 04:27
Hi!
I upgraded to rc6, and now I get different warnings, and screen.css is not generated at all.

WARNING: "blueprint/reset".sass not found. Using "blueprint/reset".css instead.
This behavior is deprecated and will be removed in a future version.
If you really need "blueprint/reset".css, import it explicitly.

WARNING: "partials/base".sass not found. Using "partials/base".css instead.
This behavior is deprecated and will be removed in a future version.
If you really need "partials/base".css, import it explicitly.

WARNING: "blueprint".sass not found. Using "blueprint".css instead.
This behavior is deprecated and will be removed in a future version.
If you really need "blueprint".css, import it explicitly.

...

Am I doing something wrong?

**Comment by chriseppstein** [comment] 2010-05-10 04:37
I hope so :) what version of sass do you have and can you please paste the relevant bits of your source files?

**Comment by marcandre** [comment] 2010-05-10 05:07
Oups, apparently forgot to restart the server...

No warnings anymore, great!

Last thing: looks like the blueprint reset css is not showing in the screen.css despite being imported. Do we need to issue a +reset or something?

**Comment by chriseppstein** [comment] 2010-05-10 05:46
Great to hear. Yes, I think that since v0.8.0, the blueprint reset requires you to add +blueprint-global-reset, but the compass reset does not.

http://compass-style.org/docs/reference/blueprint/reset/#mixin-blueprint-global-reset
