### ISSUE TITLE
Sprite-file function returns absolute path from computer root

### ISSUE THREAD

**Issue by Snugug** [Compass/compass#951] opened 2012-07-04 13:41 UTC
The docs say the sprite-file function should return the relative path from the image directory, but it instead returns the absolute path from the computer root.

**Comment by stryju** [comment] 2012-07-04 15:33
take a closer look at your `config.rb file`, especially those settings:
- `images_dir`
- `generated_images_dir`
- `http_images_dir`

( reference: http://compass-style.org/help/tutorials/configuration-reference/ )

**Comment by Snugug** [comment] 2012-07-04 15:39
I've got my images_dir set to just "images", all of the image functions produce relative paths, and `sprite-url()` produces a relative path in the url(), but `sprite-file()` produces an absolute URL from my computer root.

It seems as if `sprite-file()` is being generated off of `generated_images_dir` or `images_path` instead of `images_dir` which should provide the relative path to images.

**Comment by HNygard** [comment] 2012-07-18 11:00
Thanks a lot stryju!
Those variables should be referenced in the sprites documentation. Was about to submit a issue here on Github, but your link above solved it for me.

I have the following directory structure:

```
./build                                 Folder with compiled CSS and Sencha Touch
./build/myapp.css                       Compass compiles CSS file
./build/images/icons-44-sd963e75395.png   Sprite generated by Compass
./build/images/icons-58-sebbd49dc88.png   Sprite generated by Compass
./css/config.rb                         Compass config
./css/myapp.scss                        My SCSS file (see below)
./index.html                            Production HTML file
./index-dev.html                        Development HTML file
./images                                My image folder
./images/icons-44                       Icon set 1
./images/icons-44/delete.png
./images/icons-44/camera.png
./images/icons-44/edit.png
./images/icons-58                       Icon set 2
./images/icons-58/delete.png
./images/icons-58/camera.png
./images/icons-58/edit.png
```

Config.rb:

```
# Get the directory that this configuration file exists in
dir = File.dirname(__FILE__)

# Load the sencha-touch framework
#load File.join(dir, '..', 'touch', 'resources', 'themes')
load File.join(dir, '..', 'extjs', 'sdk', 'resources', 'themes')

# Look for any *.scss files in same directory as this file
# Place compiled *.css files in the build directory
sass_path    = dir
css_path     = File.join(dir, "..", "build")
images_path  = File.join(dir, "..", "images")
generated_images_dir = File.join("..", "build", "images")
http_generated_images_path = "images/"

output_style = :expanded
environment  = :development
```

myapp.scss (extract):

```
/* Icons */
@import "icons-44/*.png";
@include all-icons-44-sprites;
@import "icons-58/*.png";
@include all-icons-58-sprites;
```

**Comment by stryju** [comment] 2012-07-18 11:46
@Snugug any update ( progress, hopefully) ?

@HNygard glad i could help :-)

**Comment by Snugug** [comment] 2012-07-18 11:49
@stryju See my reply directly below yours. I've got everything set up correctly, but it was still spitting back an absolute URL. I wound up hacking around it by writing a str-replace SassScript function, but would much prefer to use this.

**Comment by chriseppstein** [comment] 2013-05-22 00:44
Dupe of #834

**Closed as completed by chriseppstein** 2013-05-22 00:44 UTC
