### ISSUE TITLE
Mixin variable variable?

### ISSUE THREAD

**Issue by JamyGolden** [Compass/compass#1343] opened 2013-07-18 12:21 UTC
Would it be possible to have variable function names?
For example:

```
@mixin all-sprite-properties( $sprite-name, $image){
    @include #{sprite-name}-sprite($image);
    height: #{sprite-name}-sprite-height($image);
    width: #{sprite-name}-sprite-width($image);
}
```

So the output of:

```
@include all-sprite-properties(icons, left-arrow);
```

would be

```
@include icons-sprite(left-arrow);
height: icons-sprite-height(left-arrow);
width: icons-sprite-width(left-arrow);
```

This is all assuming that what I'm trying to do doesn't already have a simple mixin.

**Comment by Snugug** [comment] 2013-07-19 15:28
This belongs in the Sass issue queue and is a duplicate of [Sass 626](https://github.com/nex3/sass/issues/626)

**Comment by chriseppstein** [comment] 2013-07-19 18:08
This just landed on master. https://github.com/nex3/sass/pull/812

**Closed as completed by chriseppstein** 2013-07-19 18:08 UTC
